/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * 
 *         Remote authentication tokens used in remote
 * authentications against HTTP Proxies and/or protected
 *         remote
 *         repositories.
 * 			
 * 
 * @version $Revision$ $Date$
 */
public class AuthenticationSettings
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field username.
     */
    private String username;

    /**
     * Field password.
     */
    private String password;

    /**
     * Field ntlmHost.
     */
    private String ntlmHost;

    /**
     * Field ntlmDomain.
     */
    private String ntlmDomain;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the ntlmDomain field.
     * 
     * @return String
     */
    public String getNtlmDomain()
    {
        return this.ntlmDomain;
    } //-- String getNtlmDomain()

    /**
     * Get the ntlmHost field.
     * 
     * @return String
     */
    public String getNtlmHost()
    {
        return this.ntlmHost;
    } //-- String getNtlmHost()

    /**
     * Get the password field.
     * 
     * @return String
     */
    public String getPassword()
    {
        return this.password;
    } //-- String getPassword()

    /**
     * Get the username field.
     * 
     * @return String
     */
    public String getUsername()
    {
        return this.username;
    } //-- String getUsername()

    /**
     * Set the ntlmDomain field.
     * 
     * @param ntlmDomain
     */
    public void setNtlmDomain( String ntlmDomain )
    {
        this.ntlmDomain = ntlmDomain;
    } //-- void setNtlmDomain( String )

    /**
     * Set the ntlmHost field.
     * 
     * @param ntlmHost
     */
    public void setNtlmHost( String ntlmHost )
    {
        this.ntlmHost = ntlmHost;
    } //-- void setNtlmHost( String )

    /**
     * Set the password field.
     * 
     * @param password
     */
    public void setPassword( String password )
    {
        this.password = password;
    } //-- void setPassword( String )

    /**
     * Set the username field.
     * 
     * @param username
     */
    public void setUsername( String username )
    {
        this.username = username;
    } //-- void setUsername( String )


}
