/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ConfigurationsListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class ConfigurationsListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<ConfigurationsListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param configurationsListResource
     */
    public void addData( ConfigurationsListResource configurationsListResource )
    {
        if ( !(configurationsListResource instanceof ConfigurationsListResource) )
        {
            throw new ClassCastException( "ConfigurationsListResourceResponse.addData(configurationsListResource) parameter must be instanceof " + ConfigurationsListResource.class.getName() );
        }
        getData().add( configurationsListResource );
    } //-- void addData( ConfigurationsListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<ConfigurationsListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<ConfigurationsListResource>();
        }

        return this.data;
    } //-- java.util.List<ConfigurationsListResource> getData()

    /**
     * Method removeData.
     * 
     * @param configurationsListResource
     */
    public void removeData( ConfigurationsListResource configurationsListResource )
    {
        if ( !(configurationsListResource instanceof ConfigurationsListResource) )
        {
            throw new ClassCastException( "ConfigurationsListResourceResponse.removeData(configurationsListResource) parameter must be instanceof " + ConfigurationsListResource.class.getName() );
        }
        getData().remove( configurationsListResource );
    } //-- void removeData( ConfigurationsListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<ConfigurationsListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
