/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ContentListDescribeRequestResource.
 * 
 * @version $Revision$ $Date$
 */
public class ContentListDescribeRequestResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field requestUrl.
     */
    private String requestUrl;

    /**
     * Field requestPath.
     */
    private String requestPath;

    /**
     * Field requestContext.
     */
    private java.util.List<String> requestContext;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addRequestContext.
     * 
     * @param string
     */
    public void addRequestContext( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "ContentListDescribeRequestResource.addRequestContext(string) parameter must be instanceof " + String.class.getName() );
        }
        getRequestContext().add( string );
    } //-- void addRequestContext( String )

    /**
     * Method getRequestContext.
     * 
     * @return List
     */
    public java.util.List<String> getRequestContext()
    {
        if ( this.requestContext == null )
        {
            this.requestContext = new java.util.ArrayList<String>();
        }

        return this.requestContext;
    } //-- java.util.List<String> getRequestContext()

    /**
     * Get the requestPath field.
     * 
     * @return String
     */
    public String getRequestPath()
    {
        return this.requestPath;
    } //-- String getRequestPath()

    /**
     * Get the requestUrl field.
     * 
     * @return String
     */
    public String getRequestUrl()
    {
        return this.requestUrl;
    } //-- String getRequestUrl()

    /**
     * Method removeRequestContext.
     * 
     * @param string
     */
    public void removeRequestContext( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "ContentListDescribeRequestResource.removeRequestContext(string) parameter must be instanceof " + String.class.getName() );
        }
        getRequestContext().remove( string );
    } //-- void removeRequestContext( String )

    /**
     * Set the requestContext field.
     * 
     * @param requestContext
     */
    public void setRequestContext( java.util.List<String> requestContext )
    {
        this.requestContext = requestContext;
    } //-- void setRequestContext( java.util.List )

    /**
     * Set the requestPath field.
     * 
     * @param requestPath
     */
    public void setRequestPath( String requestPath )
    {
        this.requestPath = requestPath;
    } //-- void setRequestPath( String )

    /**
     * Set the requestUrl field.
     * 
     * @param requestUrl
     */
    public void setRequestUrl( String requestUrl )
    {
        this.requestUrl = requestUrl;
    } //-- void setRequestUrl( String )


}
