/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ContentListDescribeResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class ContentListDescribeResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private ContentListDescribeResource data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the data field.
     * 
     * @return ContentListDescribeResource
     */
    public ContentListDescribeResource getData()
    {
        return this.data;
    } //-- ContentListDescribeResource getData()

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( ContentListDescribeResource data )
    {
        this.data = data;
    } //-- void setData( ContentListDescribeResource )


}
