/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ContentListDescribeResource.
 * 
 * @version $Revision$ $Date$
 */
public class ContentListDescribeResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field requestUrl.
     */
    private String requestUrl;

    /**
     * Field processingTimeMillis.
     */
    private long processingTimeMillis = 0L;

    /**
     * Field request.
     */
    private ContentListDescribeRequestResource request;

    /**
     * Field response.
     */
    private ContentListDescribeResponseResource response;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the processingTimeMillis field.
     * 
     * @return long
     */
    public long getProcessingTimeMillis()
    {
        return this.processingTimeMillis;
    } //-- long getProcessingTimeMillis()

    /**
     * Get the request field.
     * 
     * @return ContentListDescribeRequestResource
     */
    public ContentListDescribeRequestResource getRequest()
    {
        return this.request;
    } //-- ContentListDescribeRequestResource getRequest()

    /**
     * Get the requestUrl field.
     * 
     * @return String
     */
    public String getRequestUrl()
    {
        return this.requestUrl;
    } //-- String getRequestUrl()

    /**
     * Get the response field.
     * 
     * @return ContentListDescribeResponseResource
     */
    public ContentListDescribeResponseResource getResponse()
    {
        return this.response;
    } //-- ContentListDescribeResponseResource getResponse()

    /**
     * Set the processingTimeMillis field.
     * 
     * @param processingTimeMillis
     */
    public void setProcessingTimeMillis( long processingTimeMillis )
    {
        this.processingTimeMillis = processingTimeMillis;
    } //-- void setProcessingTimeMillis( long )

    /**
     * Set the request field.
     * 
     * @param request
     */
    public void setRequest( ContentListDescribeRequestResource request )
    {
        this.request = request;
    } //-- void setRequest( ContentListDescribeRequestResource )

    /**
     * Set the requestUrl field.
     * 
     * @param requestUrl
     */
    public void setRequestUrl( String requestUrl )
    {
        this.requestUrl = requestUrl;
    } //-- void setRequestUrl( String )

    /**
     * Set the response field.
     * 
     * @param response
     */
    public void setResponse( ContentListDescribeResponseResource response )
    {
        this.response = response;
    } //-- void setResponse( ContentListDescribeResponseResource )


}
