/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ErrorReportResponseDTO.
 * 
 * @version $Revision$ $Date$
 */
public class ErrorReportResponseDTO
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field jiraUrl.
     */
    private String jiraUrl;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the jiraUrl field.
     * 
     * @return String
     */
    public String getJiraUrl()
    {
        return this.jiraUrl;
    } //-- String getJiraUrl()

    /**
     * Set the jiraUrl field.
     * 
     * @param jiraUrl
     */
    public void setJiraUrl( String jiraUrl )
    {
        this.jiraUrl = jiraUrl;
    } //-- void setJiraUrl( String )


}
