/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ErrorReportingSettings.
 * 
 * @version $Revision$ $Date$
 */
public class ErrorReportingSettings
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field jiraUsername.
     */
    private String jiraUsername;

    /**
     * Field jiraPassword.
     */
    private String jiraPassword;

    /**
     * Field useGlobalProxy.
     */
    private boolean useGlobalProxy = false;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the jiraPassword field.
     * 
     * @return String
     */
    public String getJiraPassword()
    {
        return this.jiraPassword;
    } //-- String getJiraPassword()

    /**
     * Get the jiraUsername field.
     * 
     * @return String
     */
    public String getJiraUsername()
    {
        return this.jiraUsername;
    } //-- String getJiraUsername()

    /**
     * Get the useGlobalProxy field.
     * 
     * @return boolean
     */
    public boolean isUseGlobalProxy()
    {
        return this.useGlobalProxy;
    } //-- boolean isUseGlobalProxy()

    /**
     * Set the jiraPassword field.
     * 
     * @param jiraPassword
     */
    public void setJiraPassword( String jiraPassword )
    {
        this.jiraPassword = jiraPassword;
    } //-- void setJiraPassword( String )

    /**
     * Set the jiraUsername field.
     * 
     * @param jiraUsername
     */
    public void setJiraUsername( String jiraUsername )
    {
        this.jiraUsername = jiraUsername;
    } //-- void setJiraUsername( String )

    /**
     * Set the useGlobalProxy field.
     * 
     * @param useGlobalProxy
     */
    public void setUseGlobalProxy( boolean useGlobalProxy )
    {
        this.useGlobalProxy = useGlobalProxy;
    } //-- void setUseGlobalProxy( boolean )


}
