/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class FeedListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class FeedListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<FeedListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param feedListResource
     */
    public void addData( FeedListResource feedListResource )
    {
        if ( !(feedListResource instanceof FeedListResource) )
        {
            throw new ClassCastException( "FeedListResourceResponse.addData(feedListResource) parameter must be instanceof " + FeedListResource.class.getName() );
        }
        getData().add( feedListResource );
    } //-- void addData( FeedListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<FeedListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<FeedListResource>();
        }

        return this.data;
    } //-- java.util.List<FeedListResource> getData()

    /**
     * Method removeData.
     * 
     * @param feedListResource
     */
    public void removeData( FeedListResource feedListResource )
    {
        if ( !(feedListResource instanceof FeedListResource) )
        {
            throw new ClassCastException( "FeedListResourceResponse.removeData(feedListResource) parameter must be instanceof " + FeedListResource.class.getName() );
        }
        getData().remove( feedListResource );
    } //-- void removeData( FeedListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<FeedListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
