/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class GlobalConfigurationListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class GlobalConfigurationListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<GlobalConfigurationListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param globalConfigurationListResource
     */
    public void addData( GlobalConfigurationListResource globalConfigurationListResource )
    {
        if ( !(globalConfigurationListResource instanceof GlobalConfigurationListResource) )
        {
            throw new ClassCastException( "GlobalConfigurationListResourceResponse.addData(globalConfigurationListResource) parameter must be instanceof " + GlobalConfigurationListResource.class.getName() );
        }
        getData().add( globalConfigurationListResource );
    } //-- void addData( GlobalConfigurationListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<GlobalConfigurationListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<GlobalConfigurationListResource>();
        }

        return this.data;
    } //-- java.util.List<GlobalConfigurationListResource> getData()

    /**
     * Method removeData.
     * 
     * @param globalConfigurationListResource
     */
    public void removeData( GlobalConfigurationListResource globalConfigurationListResource )
    {
        if ( !(globalConfigurationListResource instanceof GlobalConfigurationListResource) )
        {
            throw new ClassCastException( "GlobalConfigurationListResourceResponse.removeData(globalConfigurationListResource) parameter must be instanceof " + GlobalConfigurationListResource.class.getName() );
        }
        getData().remove( globalConfigurationListResource );
    } //-- void removeData( GlobalConfigurationListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<GlobalConfigurationListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
