/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class GlobalConfigurationResource.
 * 
 * @version $Revision$ $Date$
 */
public class GlobalConfigurationResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field securityEnabled.
     */
    private boolean securityEnabled = false;

    /**
     * Field securityAnonymousAccessEnabled.
     */
    private boolean securityAnonymousAccessEnabled = false;

    /**
     * Field securityAnonymousUsername.
     */
    private String securityAnonymousUsername;

    /**
     * Field securityAnonymousPassword.
     */
    private String securityAnonymousPassword;

    /**
     * Field securityRealms.
     */
    private java.util.List<String> securityRealms;

    /**
     * Field globalConnectionSettings.
     */
    private RemoteConnectionSettings globalConnectionSettings;

    /**
     * Field smtpSettings.
     */
    private SmtpSettings smtpSettings;

    /**
     * Field globalHttpProxySettings.
     */
    private RemoteHttpProxySettings globalHttpProxySettings;

    /**
     * Field globalRestApiSettings.
     */
    private RestApiSettings globalRestApiSettings;

    /**
     * Field errorReportingSettings.
     */
    private ErrorReportingSettings errorReportingSettings;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addSecurityRealm.
     * 
     * @param string
     */
    public void addSecurityRealm( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "GlobalConfigurationResource.addSecurityRealms(string) parameter must be instanceof " + String.class.getName() );
        }
        getSecurityRealms().add( string );
    } //-- void addSecurityRealm( String )

    /**
     * Get the errorReportingSettings field.
     * 
     * @return ErrorReportingSettings
     */
    public ErrorReportingSettings getErrorReportingSettings()
    {
        return this.errorReportingSettings;
    } //-- ErrorReportingSettings getErrorReportingSettings()

    /**
     * Get the globalConnectionSettings field.
     * 
     * @return RemoteConnectionSettings
     */
    public RemoteConnectionSettings getGlobalConnectionSettings()
    {
        return this.globalConnectionSettings;
    } //-- RemoteConnectionSettings getGlobalConnectionSettings()

    /**
     * Get the globalHttpProxySettings field.
     * 
     * @return RemoteHttpProxySettings
     */
    public RemoteHttpProxySettings getGlobalHttpProxySettings()
    {
        return this.globalHttpProxySettings;
    } //-- RemoteHttpProxySettings getGlobalHttpProxySettings()

    /**
     * Get the globalRestApiSettings field.
     * 
     * @return RestApiSettings
     */
    public RestApiSettings getGlobalRestApiSettings()
    {
        return this.globalRestApiSettings;
    } //-- RestApiSettings getGlobalRestApiSettings()

    /**
     * Get the securityAnonymousPassword field.
     * 
     * @return String
     */
    public String getSecurityAnonymousPassword()
    {
        return this.securityAnonymousPassword;
    } //-- String getSecurityAnonymousPassword()

    /**
     * Get the securityAnonymousUsername field.
     * 
     * @return String
     */
    public String getSecurityAnonymousUsername()
    {
        return this.securityAnonymousUsername;
    } //-- String getSecurityAnonymousUsername()

    /**
     * Method getSecurityRealms.
     * 
     * @return List
     */
    public java.util.List<String> getSecurityRealms()
    {
        if ( this.securityRealms == null )
        {
            this.securityRealms = new java.util.ArrayList<String>();
        }

        return this.securityRealms;
    } //-- java.util.List<String> getSecurityRealms()

    /**
     * Get the smtpSettings field.
     * 
     * @return SmtpSettings
     */
    public SmtpSettings getSmtpSettings()
    {
        return this.smtpSettings;
    } //-- SmtpSettings getSmtpSettings()

    /**
     * Get the securityAnonymousAccessEnabled field.
     * 
     * @return boolean
     */
    public boolean isSecurityAnonymousAccessEnabled()
    {
        return this.securityAnonymousAccessEnabled;
    } //-- boolean isSecurityAnonymousAccessEnabled()

    /**
     * Get the securityEnabled field.
     * 
     * @return boolean
     */
    public boolean isSecurityEnabled()
    {
        return this.securityEnabled;
    } //-- boolean isSecurityEnabled()

    /**
     * Method removeSecurityRealm.
     * 
     * @param string
     */
    public void removeSecurityRealm( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "GlobalConfigurationResource.removeSecurityRealms(string) parameter must be instanceof " + String.class.getName() );
        }
        getSecurityRealms().remove( string );
    } //-- void removeSecurityRealm( String )

    /**
     * Set the errorReportingSettings field.
     * 
     * @param errorReportingSettings
     */
    public void setErrorReportingSettings( ErrorReportingSettings errorReportingSettings )
    {
        this.errorReportingSettings = errorReportingSettings;
    } //-- void setErrorReportingSettings( ErrorReportingSettings )

    /**
     * Set the globalConnectionSettings field.
     * 
     * @param globalConnectionSettings
     */
    public void setGlobalConnectionSettings( RemoteConnectionSettings globalConnectionSettings )
    {
        this.globalConnectionSettings = globalConnectionSettings;
    } //-- void setGlobalConnectionSettings( RemoteConnectionSettings )

    /**
     * Set the globalHttpProxySettings field.
     * 
     * @param globalHttpProxySettings
     */
    public void setGlobalHttpProxySettings( RemoteHttpProxySettings globalHttpProxySettings )
    {
        this.globalHttpProxySettings = globalHttpProxySettings;
    } //-- void setGlobalHttpProxySettings( RemoteHttpProxySettings )

    /**
     * Set the globalRestApiSettings field.
     * 
     * @param globalRestApiSettings
     */
    public void setGlobalRestApiSettings( RestApiSettings globalRestApiSettings )
    {
        this.globalRestApiSettings = globalRestApiSettings;
    } //-- void setGlobalRestApiSettings( RestApiSettings )

    /**
     * Set the securityAnonymousAccessEnabled field.
     * 
     * @param securityAnonymousAccessEnabled
     */
    public void setSecurityAnonymousAccessEnabled( boolean securityAnonymousAccessEnabled )
    {
        this.securityAnonymousAccessEnabled = securityAnonymousAccessEnabled;
    } //-- void setSecurityAnonymousAccessEnabled( boolean )

    /**
     * Set the securityAnonymousPassword field.
     * 
     * @param securityAnonymousPassword
     */
    public void setSecurityAnonymousPassword( String securityAnonymousPassword )
    {
        this.securityAnonymousPassword = securityAnonymousPassword;
    } //-- void setSecurityAnonymousPassword( String )

    /**
     * Set the securityAnonymousUsername field.
     * 
     * @param securityAnonymousUsername
     */
    public void setSecurityAnonymousUsername( String securityAnonymousUsername )
    {
        this.securityAnonymousUsername = securityAnonymousUsername;
    } //-- void setSecurityAnonymousUsername( String )

    /**
     * Set the securityEnabled field.
     * 
     * @param securityEnabled
     */
    public void setSecurityEnabled( boolean securityEnabled )
    {
        this.securityEnabled = securityEnabled;
    } //-- void setSecurityEnabled( boolean )

    /**
     * Set the securityRealms field.
     * 
     * @param securityRealms
     */
    public void setSecurityRealms( java.util.List<String> securityRealms )
    {
        this.securityRealms = securityRealms;
    } //-- void setSecurityRealms( java.util.List )

    /**
     * Set the smtpSettings field.
     * 
     * @param smtpSettings
     */
    public void setSmtpSettings( SmtpSettings smtpSettings )
    {
        this.smtpSettings = smtpSettings;
    } //-- void setSmtpSettings( SmtpSettings )


}
