/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class LogConfigResource.
 * 
 * @version $Revision$ $Date$
 */
public class LogConfigResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field rootLoggerLevel.
     */
    private String rootLoggerLevel;

    /**
     * Field rootLoggerAppenders.
     */
    private String rootLoggerAppenders;

    /**
     * Field fileAppenderLocation.
     */
    private String fileAppenderLocation;

    /**
     * Field fileAppenderPattern.
     */
    private String fileAppenderPattern;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the fileAppenderLocation field.
     * 
     * @return String
     */
    public String getFileAppenderLocation()
    {
        return this.fileAppenderLocation;
    } //-- String getFileAppenderLocation()

    /**
     * Get the fileAppenderPattern field.
     * 
     * @return String
     */
    public String getFileAppenderPattern()
    {
        return this.fileAppenderPattern;
    } //-- String getFileAppenderPattern()

    /**
     * Get the rootLoggerAppenders field.
     * 
     * @return String
     */
    public String getRootLoggerAppenders()
    {
        return this.rootLoggerAppenders;
    } //-- String getRootLoggerAppenders()

    /**
     * Get the rootLoggerLevel field.
     * 
     * @return String
     */
    public String getRootLoggerLevel()
    {
        return this.rootLoggerLevel;
    } //-- String getRootLoggerLevel()

    /**
     * Set the fileAppenderLocation field.
     * 
     * @param fileAppenderLocation
     */
    public void setFileAppenderLocation( String fileAppenderLocation )
    {
        this.fileAppenderLocation = fileAppenderLocation;
    } //-- void setFileAppenderLocation( String )

    /**
     * Set the fileAppenderPattern field.
     * 
     * @param fileAppenderPattern
     */
    public void setFileAppenderPattern( String fileAppenderPattern )
    {
        this.fileAppenderPattern = fileAppenderPattern;
    } //-- void setFileAppenderPattern( String )

    /**
     * Set the rootLoggerAppenders field.
     * 
     * @param rootLoggerAppenders
     */
    public void setRootLoggerAppenders( String rootLoggerAppenders )
    {
        this.rootLoggerAppenders = rootLoggerAppenders;
    } //-- void setRootLoggerAppenders( String )

    /**
     * Set the rootLoggerLevel field.
     * 
     * @param rootLoggerLevel
     */
    public void setRootLoggerLevel( String rootLoggerLevel )
    {
        this.rootLoggerLevel = rootLoggerLevel;
    } //-- void setRootLoggerLevel( String )


}
