/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class LogsListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class LogsListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<LogsListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param logsListResource
     */
    public void addData( LogsListResource logsListResource )
    {
        if ( !(logsListResource instanceof LogsListResource) )
        {
            throw new ClassCastException( "LogsListResourceResponse.addData(logsListResource) parameter must be instanceof " + LogsListResource.class.getName() );
        }
        getData().add( logsListResource );
    } //-- void addData( LogsListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<LogsListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<LogsListResource>();
        }

        return this.data;
    } //-- java.util.List<LogsListResource> getData()

    /**
     * Method removeData.
     * 
     * @param logsListResource
     */
    public void removeData( LogsListResource logsListResource )
    {
        if ( !(logsListResource instanceof LogsListResource) )
        {
            throw new ClassCastException( "LogsListResourceResponse.removeData(logsListResource) parameter must be instanceof " + LogsListResource.class.getName() );
        }
        getData().remove( logsListResource );
    } //-- void removeData( LogsListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<LogsListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
