/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class MirrorStatusResourceListResponse.
 * 
 * @version $Revision$ $Date$
 */
public class MirrorStatusResourceListResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<MirrorStatusResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param mirrorStatusResource
     */
    public void addData( MirrorStatusResource mirrorStatusResource )
    {
        if ( !(mirrorStatusResource instanceof MirrorStatusResource) )
        {
            throw new ClassCastException( "MirrorStatusResourceListResponse.addData(mirrorStatusResource) parameter must be instanceof " + MirrorStatusResource.class.getName() );
        }
        getData().add( mirrorStatusResource );
    } //-- void addData( MirrorStatusResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<MirrorStatusResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<MirrorStatusResource>();
        }

        return this.data;
    } //-- java.util.List<MirrorStatusResource> getData()

    /**
     * Method removeData.
     * 
     * @param mirrorStatusResource
     */
    public void removeData( MirrorStatusResource mirrorStatusResource )
    {
        if ( !(mirrorStatusResource instanceof MirrorStatusResource) )
        {
            throw new ClassCastException( "MirrorStatusResourceListResponse.removeData(mirrorStatusResource) parameter must be instanceof " + MirrorStatusResource.class.getName() );
        }
        getData().remove( mirrorStatusResource );
    } //-- void removeData( MirrorStatusResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<MirrorStatusResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
