/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Class NexusRepositoryTypeListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
@XmlRootElement(name="repositoryTypes")
public class NexusRepositoryTypeListResourceResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<NexusRepositoryTypeListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param nexusRepositoryTypeListResource
     */
    public void addData( NexusRepositoryTypeListResource nexusRepositoryTypeListResource )
    {
        if ( !(nexusRepositoryTypeListResource instanceof NexusRepositoryTypeListResource) )
        {
            throw new ClassCastException( "NexusRepositoryTypeListResourceResponse.addData(nexusRepositoryTypeListResource) parameter must be instanceof " + NexusRepositoryTypeListResource.class.getName() );
        }
        getData().add( nexusRepositoryTypeListResource );
    } //-- void addData( NexusRepositoryTypeListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<NexusRepositoryTypeListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<NexusRepositoryTypeListResource>();
        }

        return this.data;
    } //-- java.util.List<NexusRepositoryTypeListResource> getData()

    /**
     * Method removeData.
     * 
     * @param nexusRepositoryTypeListResource
     */
    public void removeData( NexusRepositoryTypeListResource nexusRepositoryTypeListResource )
    {
        if ( !(nexusRepositoryTypeListResource instanceof NexusRepositoryTypeListResource) )
        {
            throw new ClassCastException( "NexusRepositoryTypeListResourceResponse.removeData(nexusRepositoryTypeListResource) parameter must be instanceof " + NexusRepositoryTypeListResource.class.getName() );
        }
        getData().remove( nexusRepositoryTypeListResource );
    } //-- void removeData( NexusRepositoryTypeListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<NexusRepositoryTypeListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
