/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class NexusArtifact.
 * 
 * @version $Revision$ $Date$
 */
public class NexusArtifact
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field resourceURI.
     */
    private String resourceURI;

    /**
     * Field groupId.
     */
    private String groupId;

    /**
     * Field artifactId.
     */
    private String artifactId;

    /**
     * Field version.
     */
    private String version;

    /**
     * Field classifier.
     */
    private String classifier;

    /**
     * Field packaging.
     */
    private String packaging;

    /**
     * Field extension.
     */
    private String extension;

    /**
     * Field repoId.
     */
    private String repoId;

    /**
     * Field contextId.
     */
    private String contextId;

    /**
     * Field pomLink.
     */
    private String pomLink;

    /**
     * Field artifactLink.
     */
    private String artifactLink;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the artifactId field.
     * 
     * @return String
     */
    public String getArtifactId()
    {
        return this.artifactId;
    } //-- String getArtifactId()

    /**
     * Get the artifactLink field.
     * 
     * @return String
     */
    public String getArtifactLink()
    {
        return this.artifactLink;
    } //-- String getArtifactLink()

    /**
     * Get the classifier field.
     * 
     * @return String
     */
    public String getClassifier()
    {
        return this.classifier;
    } //-- String getClassifier()

    /**
     * Get the contextId field.
     * 
     * @return String
     */
    public String getContextId()
    {
        return this.contextId;
    } //-- String getContextId()

    /**
     * Get the extension field.
     * 
     * @return String
     */
    public String getExtension()
    {
        return this.extension;
    } //-- String getExtension()

    /**
     * Get the groupId field.
     * 
     * @return String
     */
    public String getGroupId()
    {
        return this.groupId;
    } //-- String getGroupId()

    /**
     * Get the packaging field.
     * 
     * @return String
     */
    public String getPackaging()
    {
        return this.packaging;
    } //-- String getPackaging()

    /**
     * Get the pomLink field.
     * 
     * @return String
     */
    public String getPomLink()
    {
        return this.pomLink;
    } //-- String getPomLink()

    /**
     * Get the repoId field.
     * 
     * @return String
     */
    public String getRepoId()
    {
        return this.repoId;
    } //-- String getRepoId()

    /**
     * Get the resourceURI field.
     * 
     * @return String
     */
    public String getResourceURI()
    {
        return this.resourceURI;
    } //-- String getResourceURI()

    /**
     * Get the version field.
     * 
     * @return String
     */
    public String getVersion()
    {
        return this.version;
    } //-- String getVersion()

    /**
     * Set the artifactId field.
     * 
     * @param artifactId
     */
    public void setArtifactId( String artifactId )
    {
        this.artifactId = artifactId;
    } //-- void setArtifactId( String )

    /**
     * Set the artifactLink field.
     * 
     * @param artifactLink
     */
    public void setArtifactLink( String artifactLink )
    {
        this.artifactLink = artifactLink;
    } //-- void setArtifactLink( String )

    /**
     * Set the classifier field.
     * 
     * @param classifier
     */
    public void setClassifier( String classifier )
    {
        this.classifier = classifier;
    } //-- void setClassifier( String )

    /**
     * Set the contextId field.
     * 
     * @param contextId
     */
    public void setContextId( String contextId )
    {
        this.contextId = contextId;
    } //-- void setContextId( String )

    /**
     * Set the extension field.
     * 
     * @param extension
     */
    public void setExtension( String extension )
    {
        this.extension = extension;
    } //-- void setExtension( String )

    /**
     * Set the groupId field.
     * 
     * @param groupId
     */
    public void setGroupId( String groupId )
    {
        this.groupId = groupId;
    } //-- void setGroupId( String )

    /**
     * Set the packaging field.
     * 
     * @param packaging
     */
    public void setPackaging( String packaging )
    {
        this.packaging = packaging;
    } //-- void setPackaging( String )

    /**
     * Set the pomLink field.
     * 
     * @param pomLink
     */
    public void setPomLink( String pomLink )
    {
        this.pomLink = pomLink;
    } //-- void setPomLink( String )

    /**
     * Set the repoId field.
     * 
     * @param repoId
     */
    public void setRepoId( String repoId )
    {
        this.repoId = repoId;
    } //-- void setRepoId( String )

    /**
     * Set the resourceURI field.
     * 
     * @param resourceURI
     */
    public void setResourceURI( String resourceURI )
    {
        this.resourceURI = resourceURI;
    } //-- void setResourceURI( String )

    /**
     * Set the version field.
     * 
     * @param version
     */
    public void setVersion( String version )
    {
        this.version = version;
    } //-- void setVersion( String )


}
