/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class NexusAuthenticationClientPermissions.
 * 
 * @version $Revision$ $Date$
 */
public class NexusAuthenticationClientPermissions
    extends org.sonatype.security.rest.model.AuthenticationClientPermissions
      
    implements java.io.Serializable
{

}
