/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class NFCRepositoryResource.
 * 
 * @version $Revision$ $Date$
 */
public class NFCRepositoryResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field repositoryId.
     */
    private String repositoryId;

    /**
     * Field nfcStats.
     */
    private NFCStats nfcStats;

    /**
     * Field nfcPaths.
     */
    private java.util.List<String> nfcPaths;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addNfcPath.
     * 
     * @param string
     */
    public void addNfcPath( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "NFCRepositoryResource.addNfcPaths(string) parameter must be instanceof " + String.class.getName() );
        }
        getNfcPaths().add( string );
    } //-- void addNfcPath( String )

    /**
     * Method getNfcPaths.
     * 
     * @return List
     */
    public java.util.List<String> getNfcPaths()
    {
        if ( this.nfcPaths == null )
        {
            this.nfcPaths = new java.util.ArrayList<String>();
        }

        return this.nfcPaths;
    } //-- java.util.List<String> getNfcPaths()

    /**
     * Get the nfcStats field.
     * 
     * @return NFCStats
     */
    public NFCStats getNfcStats()
    {
        return this.nfcStats;
    } //-- NFCStats getNfcStats()

    /**
     * Get the repositoryId field.
     * 
     * @return String
     */
    public String getRepositoryId()
    {
        return this.repositoryId;
    } //-- String getRepositoryId()

    /**
     * Method removeNfcPath.
     * 
     * @param string
     */
    public void removeNfcPath( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "NFCRepositoryResource.removeNfcPaths(string) parameter must be instanceof " + String.class.getName() );
        }
        getNfcPaths().remove( string );
    } //-- void removeNfcPath( String )

    /**
     * Set the nfcPaths field.
     * 
     * @param nfcPaths
     */
    public void setNfcPaths( java.util.List<String> nfcPaths )
    {
        this.nfcPaths = nfcPaths;
    } //-- void setNfcPaths( java.util.List )

    /**
     * Set the nfcStats field.
     * 
     * @param nfcStats
     */
    public void setNfcStats( NFCStats nfcStats )
    {
        this.nfcStats = nfcStats;
    } //-- void setNfcStats( NFCStats )

    /**
     * Set the repositoryId field.
     * 
     * @param repositoryId
     */
    public void setRepositoryId( String repositoryId )
    {
        this.repositoryId = repositoryId;
    } //-- void setRepositoryId( String )


}
