/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class NFCStats.
 * 
 * @version $Revision$ $Date$
 */
public class NFCStats
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field size.
     */
    private long size = 0L;

    /**
     * Field hits.
     */
    private long hits = 0L;

    /**
     * Field misses.
     */
    private long misses = 0L;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the hits field.
     * 
     * @return long
     */
    public long getHits()
    {
        return this.hits;
    } //-- long getHits()

    /**
     * Get the misses field.
     * 
     * @return long
     */
    public long getMisses()
    {
        return this.misses;
    } //-- long getMisses()

    /**
     * Get the size field.
     * 
     * @return long
     */
    public long getSize()
    {
        return this.size;
    } //-- long getSize()

    /**
     * Set the hits field.
     * 
     * @param hits
     */
    public void setHits( long hits )
    {
        this.hits = hits;
    } //-- void setHits( long )

    /**
     * Set the misses field.
     * 
     * @param misses
     */
    public void setMisses( long misses )
    {
        this.misses = misses;
    } //-- void setMisses( long )

    /**
     * Set the size field.
     * 
     * @param size
     */
    public void setSize( long size )
    {
        this.size = size;
    } //-- void setSize( long )


}
