/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class PlexusComponentListResource.
 * 
 * @version $Revision$ $Date$
 */
public class PlexusComponentListResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field roleHint.
     */
    private String roleHint;

    /**
     * Field description.
     */
    private String description;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the description field.
     * 
     * @return String
     */
    public String getDescription()
    {
        return this.description;
    } //-- String getDescription()

    /**
     * Get the roleHint field.
     * 
     * @return String
     */
    public String getRoleHint()
    {
        return this.roleHint;
    } //-- String getRoleHint()

    /**
     * Set the description field.
     * 
     * @param description
     */
    public void setDescription( String description )
    {
        this.description = description;
    } //-- void setDescription( String )

    /**
     * Set the roleHint field.
     * 
     * @param roleHint
     */
    public void setRoleHint( String roleHint )
    {
        this.roleHint = roleHint;
    } //-- void setRoleHint( String )


}
