/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class PlexusComponentListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class PlexusComponentListResourceResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<PlexusComponentListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param plexusComponentListResource
     */
    public void addData( PlexusComponentListResource plexusComponentListResource )
    {
        if ( !(plexusComponentListResource instanceof PlexusComponentListResource) )
        {
            throw new ClassCastException( "PlexusComponentListResourceResponse.addData(plexusComponentListResource) parameter must be instanceof " + PlexusComponentListResource.class.getName() );
        }
        getData().add( plexusComponentListResource );
    } //-- void addData( PlexusComponentListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<PlexusComponentListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<PlexusComponentListResource>();
        }

        return this.data;
    } //-- java.util.List<PlexusComponentListResource> getData()

    /**
     * Method removeData.
     * 
     * @param plexusComponentListResource
     */
    public void removeData( PlexusComponentListResource plexusComponentListResource )
    {
        if ( !(plexusComponentListResource instanceof PlexusComponentListResource) )
        {
            throw new ClassCastException( "PlexusComponentListResourceResponse.removeData(plexusComponentListResource) parameter must be instanceof " + PlexusComponentListResource.class.getName() );
        }
        getData().remove( plexusComponentListResource );
    } //-- void removeData( PlexusComponentListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<PlexusComponentListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
