/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * 
 *         The connections settings defines common connection
 * properties, like retries count and timeouts.
 *       
 * 
 * @version $Revision$ $Date$
 */
public class RemoteConnectionSettings
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field connectionTimeout.
     */
    private int connectionTimeout = 0;

    /**
     * Field retrievalRetryCount.
     */
    private int retrievalRetryCount = 0;

    /**
     * Field queryString.
     */
    private String queryString;

    /**
     * Field userAgentString.
     */
    private String userAgentString;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the connectionTimeout field.
     * 
     * @return int
     */
    public int getConnectionTimeout()
    {
        return this.connectionTimeout;
    } //-- int getConnectionTimeout()

    /**
     * Get the queryString field.
     * 
     * @return String
     */
    public String getQueryString()
    {
        return this.queryString;
    } //-- String getQueryString()

    /**
     * Get the retrievalRetryCount field.
     * 
     * @return int
     */
    public int getRetrievalRetryCount()
    {
        return this.retrievalRetryCount;
    } //-- int getRetrievalRetryCount()

    /**
     * Get the userAgentString field.
     * 
     * @return String
     */
    public String getUserAgentString()
    {
        return this.userAgentString;
    } //-- String getUserAgentString()

    /**
     * Set the connectionTimeout field.
     * 
     * @param connectionTimeout
     */
    public void setConnectionTimeout( int connectionTimeout )
    {
        this.connectionTimeout = connectionTimeout;
    } //-- void setConnectionTimeout( int )

    /**
     * Set the queryString field.
     * 
     * @param queryString
     */
    public void setQueryString( String queryString )
    {
        this.queryString = queryString;
    } //-- void setQueryString( String )

    /**
     * Set the retrievalRetryCount field.
     * 
     * @param retrievalRetryCount
     */
    public void setRetrievalRetryCount( int retrievalRetryCount )
    {
        this.retrievalRetryCount = retrievalRetryCount;
    } //-- void setRetrievalRetryCount( int )

    /**
     * Set the userAgentString field.
     * 
     * @param userAgentString
     */
    public void setUserAgentString( String userAgentString )
    {
        this.userAgentString = userAgentString;
    } //-- void setUserAgentString( String )


}
