/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * The HTTP Proxy defines proxies used to access the internet.
 * 
 * @version $Revision$ $Date$
 */
public class RemoteHttpProxySettings
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field proxyHostname.
     */
    private String proxyHostname;

    /**
     * Field proxyPort.
     */
    private int proxyPort = 0;

    /**
     * Field authentication.
     */
    private AuthenticationSettings authentication;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the authentication field.
     * 
     * @return AuthenticationSettings
     */
    public AuthenticationSettings getAuthentication()
    {
        return this.authentication;
    } //-- AuthenticationSettings getAuthentication()

    /**
     * Get the proxyHostname field.
     * 
     * @return String
     */
    public String getProxyHostname()
    {
        return this.proxyHostname;
    } //-- String getProxyHostname()

    /**
     * Get the proxyPort field.
     * 
     * @return int
     */
    public int getProxyPort()
    {
        return this.proxyPort;
    } //-- int getProxyPort()

    /**
     * Set the authentication field.
     * 
     * @param authentication
     */
    public void setAuthentication( AuthenticationSettings authentication )
    {
        this.authentication = authentication;
    } //-- void setAuthentication( AuthenticationSettings )

    /**
     * Set the proxyHostname field.
     * 
     * @param proxyHostname
     */
    public void setProxyHostname( String proxyHostname )
    {
        this.proxyHostname = proxyHostname;
    } //-- void setProxyHostname( String )

    /**
     * Set the proxyPort field.
     * 
     * @param proxyPort
     */
    public void setProxyPort( int proxyPort )
    {
        this.proxyPort = proxyPort;
    } //-- void setProxyPort( int )


}
