/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryShadowResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryShadowResource
    extends RepositoryBaseResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field shadowOf.
     */
    private String shadowOf;

    /**
     * Field syncAtStartup.
     */
    private boolean syncAtStartup = false;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the shadowOf field.
     * 
     * @return String
     */
    public String getShadowOf()
    {
        return this.shadowOf;
    } //-- String getShadowOf()

    /**
     * Get the syncAtStartup field.
     * 
     * @return boolean
     */
    public boolean isSyncAtStartup()
    {
        return this.syncAtStartup;
    } //-- boolean isSyncAtStartup()

    /**
     * Set the shadowOf field.
     * 
     * @param shadowOf
     */
    public void setShadowOf( String shadowOf )
    {
        this.shadowOf = shadowOf;
    } //-- void setShadowOf( String )

    /**
     * Set the syncAtStartup field.
     * 
     * @param syncAtStartup
     */
    public void setSyncAtStartup( boolean syncAtStartup )
    {
        this.syncAtStartup = syncAtStartup;
    } //-- void setSyncAtStartup( boolean )


}
