/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryResource
    extends RepositoryBaseResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field writePolicy.
     */
    private String writePolicy;

    /**
     * Field browseable.
     */
    private boolean browseable = false;

    /**
     * Field indexable.
     */
    private boolean indexable = false;

    /**
     * Field notFoundCacheTTL.
     */
    private int notFoundCacheTTL = 0;

    /**
     * Field repoPolicy.
     */
    private String repoPolicy;

    /**
     * Field checksumPolicy.
     */
    private String checksumPolicy;

    /**
     * Field downloadRemoteIndexes.
     */
    private boolean downloadRemoteIndexes = false;

    /**
     * Field overrideLocalStorageUrl.
     */
    private String overrideLocalStorageUrl;

    /**
     * Field defaultLocalStorageUrl.
     */
    private String defaultLocalStorageUrl;

    /**
     * Field remoteStorage.
     */
    private RepositoryResourceRemoteStorage remoteStorage;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the checksumPolicy field.
     * 
     * @return String
     */
    public String getChecksumPolicy()
    {
        return this.checksumPolicy;
    } //-- String getChecksumPolicy()

    /**
     * Get the defaultLocalStorageUrl field.
     * 
     * @return String
     */
    public String getDefaultLocalStorageUrl()
    {
        return this.defaultLocalStorageUrl;
    } //-- String getDefaultLocalStorageUrl()

    /**
     * Get the notFoundCacheTTL field.
     * 
     * @return int
     */
    public int getNotFoundCacheTTL()
    {
        return this.notFoundCacheTTL;
    } //-- int getNotFoundCacheTTL()

    /**
     * Get the overrideLocalStorageUrl field.
     * 
     * @return String
     */
    public String getOverrideLocalStorageUrl()
    {
        return this.overrideLocalStorageUrl;
    } //-- String getOverrideLocalStorageUrl()

    /**
     * Get the remoteStorage field.
     * 
     * @return RepositoryResourceRemoteStorage
     */
    public RepositoryResourceRemoteStorage getRemoteStorage()
    {
        return this.remoteStorage;
    } //-- RepositoryResourceRemoteStorage getRemoteStorage()

    /**
     * Get the repoPolicy field.
     * 
     * @return String
     */
    public String getRepoPolicy()
    {
        return this.repoPolicy;
    } //-- String getRepoPolicy()

    /**
     * Get the writePolicy field.
     * 
     * @return String
     */
    public String getWritePolicy()
    {
        return this.writePolicy;
    } //-- String getWritePolicy()

    /**
     * Get the browseable field.
     * 
     * @return boolean
     */
    public boolean isBrowseable()
    {
        return this.browseable;
    } //-- boolean isBrowseable()

    /**
     * Get the downloadRemoteIndexes field.
     * 
     * @return boolean
     */
    public boolean isDownloadRemoteIndexes()
    {
        return this.downloadRemoteIndexes;
    } //-- boolean isDownloadRemoteIndexes()

    /**
     * Get the indexable field.
     * 
     * @return boolean
     */
    public boolean isIndexable()
    {
        return this.indexable;
    } //-- boolean isIndexable()

    /**
     * Set the browseable field.
     * 
     * @param browseable
     */
    public void setBrowseable( boolean browseable )
    {
        this.browseable = browseable;
    } //-- void setBrowseable( boolean )

    /**
     * Set the checksumPolicy field.
     * 
     * @param checksumPolicy
     */
    public void setChecksumPolicy( String checksumPolicy )
    {
        this.checksumPolicy = checksumPolicy;
    } //-- void setChecksumPolicy( String )

    /**
     * Set the defaultLocalStorageUrl field.
     * 
     * @param defaultLocalStorageUrl
     */
    public void setDefaultLocalStorageUrl( String defaultLocalStorageUrl )
    {
        this.defaultLocalStorageUrl = defaultLocalStorageUrl;
    } //-- void setDefaultLocalStorageUrl( String )

    /**
     * Set the downloadRemoteIndexes field.
     * 
     * @param downloadRemoteIndexes
     */
    public void setDownloadRemoteIndexes( boolean downloadRemoteIndexes )
    {
        this.downloadRemoteIndexes = downloadRemoteIndexes;
    } //-- void setDownloadRemoteIndexes( boolean )

    /**
     * Set the indexable field.
     * 
     * @param indexable
     */
    public void setIndexable( boolean indexable )
    {
        this.indexable = indexable;
    } //-- void setIndexable( boolean )

    /**
     * Set the notFoundCacheTTL field.
     * 
     * @param notFoundCacheTTL
     */
    public void setNotFoundCacheTTL( int notFoundCacheTTL )
    {
        this.notFoundCacheTTL = notFoundCacheTTL;
    } //-- void setNotFoundCacheTTL( int )

    /**
     * Set the overrideLocalStorageUrl field.
     * 
     * @param overrideLocalStorageUrl
     */
    public void setOverrideLocalStorageUrl( String overrideLocalStorageUrl )
    {
        this.overrideLocalStorageUrl = overrideLocalStorageUrl;
    } //-- void setOverrideLocalStorageUrl( String )

    /**
     * Set the remoteStorage field.
     * 
     * @param remoteStorage
     */
    public void setRemoteStorage( RepositoryResourceRemoteStorage remoteStorage )
    {
        this.remoteStorage = remoteStorage;
    } //-- void setRemoteStorage( RepositoryResourceRemoteStorage )

    /**
     * Set the repoPolicy field.
     * 
     * @param repoPolicy
     */
    public void setRepoPolicy( String repoPolicy )
    {
        this.repoPolicy = repoPolicy;
    } //-- void setRepoPolicy( String )

    /**
     * Set the writePolicy field.
     * 
     * @param writePolicy
     */
    public void setWritePolicy( String writePolicy )
    {
        this.writePolicy = writePolicy;
    } //-- void setWritePolicy( String )


}
