/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryDependentStatusResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryDependentStatusResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field id.
     */
    private String id;

    /**
     * Field repoType.
     */
    private String repoType;

    /**
     * Field format.
     */
    private String format;

    /**
     * Field localStatus.
     */
    private String localStatus;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the format field.
     * 
     * @return String
     */
    public String getFormat()
    {
        return this.format;
    } //-- String getFormat()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the localStatus field.
     * 
     * @return String
     */
    public String getLocalStatus()
    {
        return this.localStatus;
    } //-- String getLocalStatus()

    /**
     * Get the repoType field.
     * 
     * @return String
     */
    public String getRepoType()
    {
        return this.repoType;
    } //-- String getRepoType()

    /**
     * Set the format field.
     * 
     * @param format
     */
    public void setFormat( String format )
    {
        this.format = format;
    } //-- void setFormat( String )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the localStatus field.
     * 
     * @param localStatus
     */
    public void setLocalStatus( String localStatus )
    {
        this.localStatus = localStatus;
    } //-- void setLocalStatus( String )

    /**
     * Set the repoType field.
     * 
     * @param repoType
     */
    public void setRepoType( String repoType )
    {
        this.repoType = repoType;
    } //-- void setRepoType( String )


}
