/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryRouteListResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryRouteListResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field resourceURI.
     */
    private String resourceURI;

    /**
     * Field groupId.
     */
    private String groupId;

    /**
     * Field ruleType.
     */
    private String ruleType;

    /**
     * Field pattern.
     */
    private String pattern;

    /**
     * Field repositories.
     */
    private java.util.List<RepositoryRouteMemberRepository> repositories;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addRepository.
     * 
     * @param repositoryRouteMemberRepository
     */
    public void addRepository( RepositoryRouteMemberRepository repositoryRouteMemberRepository )
    {
        if ( !(repositoryRouteMemberRepository instanceof RepositoryRouteMemberRepository) )
        {
            throw new ClassCastException( "RepositoryRouteListResource.addRepositories(repositoryRouteMemberRepository) parameter must be instanceof " + RepositoryRouteMemberRepository.class.getName() );
        }
        getRepositories().add( repositoryRouteMemberRepository );
    } //-- void addRepository( RepositoryRouteMemberRepository )

    /**
     * Get the groupId field.
     * 
     * @return String
     */
    public String getGroupId()
    {
        return this.groupId;
    } //-- String getGroupId()

    /**
     * Get the pattern field.
     * 
     * @return String
     */
    public String getPattern()
    {
        return this.pattern;
    } //-- String getPattern()

    /**
     * Method getRepositories.
     * 
     * @return List
     */
    public java.util.List<RepositoryRouteMemberRepository> getRepositories()
    {
        if ( this.repositories == null )
        {
            this.repositories = new java.util.ArrayList<RepositoryRouteMemberRepository>();
        }

        return this.repositories;
    } //-- java.util.List<RepositoryRouteMemberRepository> getRepositories()

    /**
     * Get the resourceURI field.
     * 
     * @return String
     */
    public String getResourceURI()
    {
        return this.resourceURI;
    } //-- String getResourceURI()

    /**
     * Get the ruleType field.
     * 
     * @return String
     */
    public String getRuleType()
    {
        return this.ruleType;
    } //-- String getRuleType()

    /**
     * Method removeRepository.
     * 
     * @param repositoryRouteMemberRepository
     */
    public void removeRepository( RepositoryRouteMemberRepository repositoryRouteMemberRepository )
    {
        if ( !(repositoryRouteMemberRepository instanceof RepositoryRouteMemberRepository) )
        {
            throw new ClassCastException( "RepositoryRouteListResource.removeRepositories(repositoryRouteMemberRepository) parameter must be instanceof " + RepositoryRouteMemberRepository.class.getName() );
        }
        getRepositories().remove( repositoryRouteMemberRepository );
    } //-- void removeRepository( RepositoryRouteMemberRepository )

    /**
     * Set the groupId field.
     * 
     * @param groupId
     */
    public void setGroupId( String groupId )
    {
        this.groupId = groupId;
    } //-- void setGroupId( String )

    /**
     * Set the pattern field.
     * 
     * @param pattern
     */
    public void setPattern( String pattern )
    {
        this.pattern = pattern;
    } //-- void setPattern( String )

    /**
     * Set the repositories field.
     * 
     * @param repositories
     */
    public void setRepositories( java.util.List<RepositoryRouteMemberRepository> repositories )
    {
        this.repositories = repositories;
    } //-- void setRepositories( java.util.List )

    /**
     * Set the resourceURI field.
     * 
     * @param resourceURI
     */
    public void setResourceURI( String resourceURI )
    {
        this.resourceURI = resourceURI;
    } //-- void setResourceURI( String )

    /**
     * Set the ruleType field.
     * 
     * @param ruleType
     */
    public void setRuleType( String ruleType )
    {
        this.ruleType = ruleType;
    } //-- void setRuleType( String )


}
