/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryStatusListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryStatusListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<RepositoryStatusListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param repositoryStatusListResource
     */
    public void addData( RepositoryStatusListResource repositoryStatusListResource )
    {
        if ( !(repositoryStatusListResource instanceof RepositoryStatusListResource) )
        {
            throw new ClassCastException( "RepositoryStatusListResourceResponse.addData(repositoryStatusListResource) parameter must be instanceof " + RepositoryStatusListResource.class.getName() );
        }
        getData().add( repositoryStatusListResource );
    } //-- void addData( RepositoryStatusListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<RepositoryStatusListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<RepositoryStatusListResource>();
        }

        return this.data;
    } //-- java.util.List<RepositoryStatusListResource> getData()

    /**
     * Method removeData.
     * 
     * @param repositoryStatusListResource
     */
    public void removeData( RepositoryStatusListResource repositoryStatusListResource )
    {
        if ( !(repositoryStatusListResource instanceof RepositoryStatusListResource) )
        {
            throw new ClassCastException( "RepositoryStatusListResourceResponse.removeData(repositoryStatusListResource) parameter must be instanceof " + RepositoryStatusListResource.class.getName() );
        }
        getData().remove( repositoryStatusListResource );
    } //-- void removeData( RepositoryStatusListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<RepositoryStatusListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
