/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryGroupListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryGroupListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<RepositoryGroupListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param repositoryGroupListResource
     */
    public void addData( RepositoryGroupListResource repositoryGroupListResource )
    {
        if ( !(repositoryGroupListResource instanceof RepositoryGroupListResource) )
        {
            throw new ClassCastException( "RepositoryGroupListResourceResponse.addData(repositoryGroupListResource) parameter must be instanceof " + RepositoryGroupListResource.class.getName() );
        }
        getData().add( repositoryGroupListResource );
    } //-- void addData( RepositoryGroupListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<RepositoryGroupListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<RepositoryGroupListResource>();
        }

        return this.data;
    } //-- java.util.List<RepositoryGroupListResource> getData()

    /**
     * Method removeData.
     * 
     * @param repositoryGroupListResource
     */
    public void removeData( RepositoryGroupListResource repositoryGroupListResource )
    {
        if ( !(repositoryGroupListResource instanceof RepositoryGroupListResource) )
        {
            throw new ClassCastException( "RepositoryGroupListResourceResponse.removeData(repositoryGroupListResource) parameter must be instanceof " + RepositoryGroupListResource.class.getName() );
        }
        getData().remove( repositoryGroupListResource );
    } //-- void removeData( RepositoryGroupListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<RepositoryGroupListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
