/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Class RepositoryListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
@XmlRootElement(name="repositories")
public class RepositoryListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<RepositoryListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param repositoryListResource
     */
    public void addData( RepositoryListResource repositoryListResource )
    {
        if ( !(repositoryListResource instanceof RepositoryListResource) )
        {
            throw new ClassCastException( "RepositoryListResourceResponse.addData(repositoryListResource) parameter must be instanceof " + RepositoryListResource.class.getName() );
        }
        getData().add( repositoryListResource );
    } //-- void addData( RepositoryListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<RepositoryListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<RepositoryListResource>();
        }

        return this.data;
    } //-- java.util.List<RepositoryListResource> getData()

    /**
     * Method removeData.
     * 
     * @param repositoryListResource
     */
    public void removeData( RepositoryListResource repositoryListResource )
    {
        if ( !(repositoryListResource instanceof RepositoryListResource) )
        {
            throw new ClassCastException( "RepositoryListResourceResponse.removeData(repositoryListResource) parameter must be instanceof " + RepositoryListResource.class.getName() );
        }
        getData().remove( repositoryListResource );
    } //-- void removeData( RepositoryListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<RepositoryListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
