/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryTargetListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryTargetListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<RepositoryTargetListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param repositoryTargetListResource
     */
    public void addData( RepositoryTargetListResource repositoryTargetListResource )
    {
        if ( !(repositoryTargetListResource instanceof RepositoryTargetListResource) )
        {
            throw new ClassCastException( "RepositoryTargetListResourceResponse.addData(repositoryTargetListResource) parameter must be instanceof " + RepositoryTargetListResource.class.getName() );
        }
        getData().add( repositoryTargetListResource );
    } //-- void addData( RepositoryTargetListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<RepositoryTargetListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<RepositoryTargetListResource>();
        }

        return this.data;
    } //-- java.util.List<RepositoryTargetListResource> getData()

    /**
     * Method removeData.
     * 
     * @param repositoryTargetListResource
     */
    public void removeData( RepositoryTargetListResource repositoryTargetListResource )
    {
        if ( !(repositoryTargetListResource instanceof RepositoryTargetListResource) )
        {
            throw new ClassCastException( "RepositoryTargetListResourceResponse.removeData(repositoryTargetListResource) parameter must be instanceof " + RepositoryTargetListResource.class.getName() );
        }
        getData().remove( repositoryTargetListResource );
    } //-- void removeData( RepositoryTargetListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<RepositoryTargetListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
