/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryResourceRemoteStorage.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryResourceRemoteStorage
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field remoteStorageUrl.
     */
    private String remoteStorageUrl;

    /**
     * Field authentication.
     */
    private AuthenticationSettings authentication;

    /**
     * Field connectionSettings.
     */
    private RemoteConnectionSettings connectionSettings;

    /**
     * Field httpProxySettings.
     */
    private RemoteHttpProxySettings httpProxySettings;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the authentication field.
     * 
     * @return AuthenticationSettings
     */
    public AuthenticationSettings getAuthentication()
    {
        return this.authentication;
    } //-- AuthenticationSettings getAuthentication()

    /**
     * Get the connectionSettings field.
     * 
     * @return RemoteConnectionSettings
     */
    public RemoteConnectionSettings getConnectionSettings()
    {
        return this.connectionSettings;
    } //-- RemoteConnectionSettings getConnectionSettings()

    /**
     * Get the httpProxySettings field.
     * 
     * @return RemoteHttpProxySettings
     */
    public RemoteHttpProxySettings getHttpProxySettings()
    {
        return this.httpProxySettings;
    } //-- RemoteHttpProxySettings getHttpProxySettings()

    /**
     * Get the remoteStorageUrl field.
     * 
     * @return String
     */
    public String getRemoteStorageUrl()
    {
        return this.remoteStorageUrl;
    } //-- String getRemoteStorageUrl()

    /**
     * Set the authentication field.
     * 
     * @param authentication
     */
    public void setAuthentication( AuthenticationSettings authentication )
    {
        this.authentication = authentication;
    } //-- void setAuthentication( AuthenticationSettings )

    /**
     * Set the connectionSettings field.
     * 
     * @param connectionSettings
     */
    public void setConnectionSettings( RemoteConnectionSettings connectionSettings )
    {
        this.connectionSettings = connectionSettings;
    } //-- void setConnectionSettings( RemoteConnectionSettings )

    /**
     * Set the httpProxySettings field.
     * 
     * @param httpProxySettings
     */
    public void setHttpProxySettings( RemoteHttpProxySettings httpProxySettings )
    {
        this.httpProxySettings = httpProxySettings;
    } //-- void setHttpProxySettings( RemoteHttpProxySettings )

    /**
     * Set the remoteStorageUrl field.
     * 
     * @param remoteStorageUrl
     */
    public void setRemoteStorageUrl( String remoteStorageUrl )
    {
        this.remoteStorageUrl = remoteStorageUrl;
    } //-- void setRemoteStorageUrl( String )


}
