/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryStatusResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryStatusResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field id.
     */
    private String id;

    /**
     * Field repoType.
     */
    private String repoType;

    /**
     * Field format.
     */
    private String format;

    /**
     * Field localStatus.
     */
    private String localStatus;

    /**
     * Field remoteStatus.
     */
    private String remoteStatus;

    /**
     * Field proxyMode.
     */
    private String proxyMode;

    /**
     * Field dependentRepos.
     */
    private java.util.List<RepositoryDependentStatusResource> dependentRepos;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addDependentRepo.
     * 
     * @param repositoryDependentStatusResource
     */
    public void addDependentRepo( RepositoryDependentStatusResource repositoryDependentStatusResource )
    {
        if ( !(repositoryDependentStatusResource instanceof RepositoryDependentStatusResource) )
        {
            throw new ClassCastException( "RepositoryStatusResource.addDependentRepos(repositoryDependentStatusResource) parameter must be instanceof " + RepositoryDependentStatusResource.class.getName() );
        }
        getDependentRepos().add( repositoryDependentStatusResource );
    } //-- void addDependentRepo( RepositoryDependentStatusResource )

    /**
     * Method getDependentRepos.
     * 
     * @return List
     */
    public java.util.List<RepositoryDependentStatusResource> getDependentRepos()
    {
        if ( this.dependentRepos == null )
        {
            this.dependentRepos = new java.util.ArrayList<RepositoryDependentStatusResource>();
        }

        return this.dependentRepos;
    } //-- java.util.List<RepositoryDependentStatusResource> getDependentRepos()

    /**
     * Get the format field.
     * 
     * @return String
     */
    public String getFormat()
    {
        return this.format;
    } //-- String getFormat()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the localStatus field.
     * 
     * @return String
     */
    public String getLocalStatus()
    {
        return this.localStatus;
    } //-- String getLocalStatus()

    /**
     * Get the proxyMode field.
     * 
     * @return String
     */
    public String getProxyMode()
    {
        return this.proxyMode;
    } //-- String getProxyMode()

    /**
     * Get the remoteStatus field.
     * 
     * @return String
     */
    public String getRemoteStatus()
    {
        return this.remoteStatus;
    } //-- String getRemoteStatus()

    /**
     * Get the repoType field.
     * 
     * @return String
     */
    public String getRepoType()
    {
        return this.repoType;
    } //-- String getRepoType()

    /**
     * Method removeDependentRepo.
     * 
     * @param repositoryDependentStatusResource
     */
    public void removeDependentRepo( RepositoryDependentStatusResource repositoryDependentStatusResource )
    {
        if ( !(repositoryDependentStatusResource instanceof RepositoryDependentStatusResource) )
        {
            throw new ClassCastException( "RepositoryStatusResource.removeDependentRepos(repositoryDependentStatusResource) parameter must be instanceof " + RepositoryDependentStatusResource.class.getName() );
        }
        getDependentRepos().remove( repositoryDependentStatusResource );
    } //-- void removeDependentRepo( RepositoryDependentStatusResource )

    /**
     * Set the dependentRepos field.
     * 
     * @param dependentRepos
     */
    public void setDependentRepos( java.util.List<RepositoryDependentStatusResource> dependentRepos )
    {
        this.dependentRepos = dependentRepos;
    } //-- void setDependentRepos( java.util.List )

    /**
     * Set the format field.
     * 
     * @param format
     */
    public void setFormat( String format )
    {
        this.format = format;
    } //-- void setFormat( String )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the localStatus field.
     * 
     * @param localStatus
     */
    public void setLocalStatus( String localStatus )
    {
        this.localStatus = localStatus;
    } //-- void setLocalStatus( String )

    /**
     * Set the proxyMode field.
     * 
     * @param proxyMode
     */
    public void setProxyMode( String proxyMode )
    {
        this.proxyMode = proxyMode;
    } //-- void setProxyMode( String )

    /**
     * Set the remoteStatus field.
     * 
     * @param remoteStatus
     */
    public void setRemoteStatus( String remoteStatus )
    {
        this.remoteStatus = remoteStatus;
    } //-- void setRemoteStatus( String )

    /**
     * Set the repoType field.
     * 
     * @param repoType
     */
    public void setRepoType( String repoType )
    {
        this.repoType = repoType;
    } //-- void setRepoType( String )


}
