/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryGroupListResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryGroupListResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field resourceURI.
     */
    private String resourceURI;

    /**
     * Field contentResourceURI.
     */
    private String contentResourceURI;

    /**
     * Field id.
     */
    private String id;

    /**
     * Field name.
     */
    private String name;

    /**
     * Field format.
     */
    private String format;

    /**
     * Field exposed.
     */
    private boolean exposed = false;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the contentResourceURI field.
     * 
     * @return String
     */
    public String getContentResourceURI()
    {
        return this.contentResourceURI;
    } //-- String getContentResourceURI()

    /**
     * Get the format field.
     * 
     * @return String
     */
    public String getFormat()
    {
        return this.format;
    } //-- String getFormat()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the name field.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Get the resourceURI field.
     * 
     * @return String
     */
    public String getResourceURI()
    {
        return this.resourceURI;
    } //-- String getResourceURI()

    /**
     * Get the exposed field.
     * 
     * @return boolean
     */
    public boolean isExposed()
    {
        return this.exposed;
    } //-- boolean isExposed()

    /**
     * Set the contentResourceURI field.
     * 
     * @param contentResourceURI
     */
    public void setContentResourceURI( String contentResourceURI )
    {
        this.contentResourceURI = contentResourceURI;
    } //-- void setContentResourceURI( String )

    /**
     * Set the exposed field.
     * 
     * @param exposed
     */
    public void setExposed( boolean exposed )
    {
        this.exposed = exposed;
    } //-- void setExposed( boolean )

    /**
     * Set the format field.
     * 
     * @param format
     */
    public void setFormat( String format )
    {
        this.format = format;
    } //-- void setFormat( String )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the name field.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set the resourceURI field.
     * 
     * @param resourceURI
     */
    public void setResourceURI( String resourceURI )
    {
        this.resourceURI = resourceURI;
    } //-- void setResourceURI( String )


}
