/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryContentClassListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryContentClassListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<RepositoryContentClassListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param repositoryContentClassListResource
     */
    public void addData( RepositoryContentClassListResource repositoryContentClassListResource )
    {
        if ( !(repositoryContentClassListResource instanceof RepositoryContentClassListResource) )
        {
            throw new ClassCastException( "RepositoryContentClassListResourceResponse.addData(repositoryContentClassListResource) parameter must be instanceof " + RepositoryContentClassListResource.class.getName() );
        }
        getData().add( repositoryContentClassListResource );
    } //-- void addData( RepositoryContentClassListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<RepositoryContentClassListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<RepositoryContentClassListResource>();
        }

        return this.data;
    } //-- java.util.List<RepositoryContentClassListResource> getData()

    /**
     * Method removeData.
     * 
     * @param repositoryContentClassListResource
     */
    public void removeData( RepositoryContentClassListResource repositoryContentClassListResource )
    {
        if ( !(repositoryContentClassListResource instanceof RepositoryContentClassListResource) )
        {
            throw new ClassCastException( "RepositoryContentClassListResourceResponse.removeData(repositoryContentClassListResource) parameter must be instanceof " + RepositoryContentClassListResource.class.getName() );
        }
        getData().remove( repositoryContentClassListResource );
    } //-- void removeData( RepositoryContentClassListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<RepositoryContentClassListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
