/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryRouteListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryRouteListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<RepositoryRouteListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param repositoryRouteListResource
     */
    public void addData( RepositoryRouteListResource repositoryRouteListResource )
    {
        if ( !(repositoryRouteListResource instanceof RepositoryRouteListResource) )
        {
            throw new ClassCastException( "RepositoryRouteListResourceResponse.addData(repositoryRouteListResource) parameter must be instanceof " + RepositoryRouteListResource.class.getName() );
        }
        getData().add( repositoryRouteListResource );
    } //-- void addData( RepositoryRouteListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<RepositoryRouteListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<RepositoryRouteListResource>();
        }

        return this.data;
    } //-- java.util.List<RepositoryRouteListResource> getData()

    /**
     * Method removeData.
     * 
     * @param repositoryRouteListResource
     */
    public void removeData( RepositoryRouteListResource repositoryRouteListResource )
    {
        if ( !(repositoryRouteListResource instanceof RepositoryRouteListResource) )
        {
            throw new ClassCastException( "RepositoryRouteListResourceResponse.removeData(repositoryRouteListResource) parameter must be instanceof " + RepositoryRouteListResource.class.getName() );
        }
        getData().remove( repositoryRouteListResource );
    } //-- void removeData( RepositoryRouteListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<RepositoryRouteListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
