/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryProxyResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryProxyResource
    extends RepositoryResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field artifactMaxAge.
     */
    private int artifactMaxAge = 0;

    /**
     * Field metadataMaxAge.
     */
    private int metadataMaxAge = 0;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the artifactMaxAge field.
     * 
     * @return int
     */
    public int getArtifactMaxAge()
    {
        return this.artifactMaxAge;
    } //-- int getArtifactMaxAge()

    /**
     * Get the metadataMaxAge field.
     * 
     * @return int
     */
    public int getMetadataMaxAge()
    {
        return this.metadataMaxAge;
    } //-- int getMetadataMaxAge()

    /**
     * Set the artifactMaxAge field.
     * 
     * @param artifactMaxAge
     */
    public void setArtifactMaxAge( int artifactMaxAge )
    {
        this.artifactMaxAge = artifactMaxAge;
    } //-- void setArtifactMaxAge( int )

    /**
     * Set the metadataMaxAge field.
     * 
     * @param metadataMaxAge
     */
    public void setMetadataMaxAge( int metadataMaxAge )
    {
        this.metadataMaxAge = metadataMaxAge;
    } //-- void setMetadataMaxAge( int )


}
