/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryContentClassListResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryContentClassListResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field contentClass.
     */
    private String contentClass;

    /**
     * Field name.
     */
    private String name;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the contentClass field.
     * 
     * @return String
     */
    public String getContentClass()
    {
        return this.contentClass;
    } //-- String getContentClass()

    /**
     * Get the name field.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Set the contentClass field.
     * 
     * @param contentClass
     */
    public void setContentClass( String contentClass )
    {
        this.contentClass = contentClass;
    } //-- void setContentClass( String )

    /**
     * Set the name field.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )


}
