/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryBaseResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryBaseResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field contentResourceURI.
     */
    private String contentResourceURI;

    /**
     * Field id.
     */
    private String id;

    /**
     * Field name.
     */
    private String name;

    /**
     * Field provider.
     */
    private String provider;

    /**
     * Field providerRole.
     */
    private String providerRole;

    /**
     * Field format.
     */
    private String format;

    /**
     * Field repoType.
     */
    private String repoType;

    /**
     * Field exposed.
     */
    private boolean exposed = false;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the contentResourceURI field.
     * 
     * @return String
     */
    public String getContentResourceURI()
    {
        return this.contentResourceURI;
    } //-- String getContentResourceURI()

    /**
     * Get the format field.
     * 
     * @return String
     */
    public String getFormat()
    {
        return this.format;
    } //-- String getFormat()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the name field.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Get the provider field.
     * 
     * @return String
     */
    public String getProvider()
    {
        return this.provider;
    } //-- String getProvider()

    /**
     * Get the providerRole field.
     * 
     * @return String
     */
    public String getProviderRole()
    {
        return this.providerRole;
    } //-- String getProviderRole()

    /**
     * Get the repoType field.
     * 
     * @return String
     */
    public String getRepoType()
    {
        return this.repoType;
    } //-- String getRepoType()

    /**
     * Get the exposed field.
     * 
     * @return boolean
     */
    public boolean isExposed()
    {
        return this.exposed;
    } //-- boolean isExposed()

    /**
     * Set the contentResourceURI field.
     * 
     * @param contentResourceURI
     */
    public void setContentResourceURI( String contentResourceURI )
    {
        this.contentResourceURI = contentResourceURI;
    } //-- void setContentResourceURI( String )

    /**
     * Set the exposed field.
     * 
     * @param exposed
     */
    public void setExposed( boolean exposed )
    {
        this.exposed = exposed;
    } //-- void setExposed( boolean )

    /**
     * Set the format field.
     * 
     * @param format
     */
    public void setFormat( String format )
    {
        this.format = format;
    } //-- void setFormat( String )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the name field.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set the provider field.
     * 
     * @param provider
     */
    public void setProvider( String provider )
    {
        this.provider = provider;
    } //-- void setProvider( String )

    /**
     * Set the providerRole field.
     * 
     * @param providerRole
     */
    public void setProviderRole( String providerRole )
    {
        this.providerRole = providerRole;
    } //-- void setProviderRole( String )

    /**
     * Set the repoType field.
     * 
     * @param repoType
     */
    public void setRepoType( String repoType )
    {
        this.repoType = repoType;
    } //-- void setRepoType( String )


}
