/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryMetaResource.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryMetaResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field id.
     */
    private String id;

    /**
     * Field repoType.
     */
    private String repoType;

    /**
     * Field format.
     */
    private String format;

    /**
     * Field sizeOnDisk.
     */
    private long sizeOnDisk = 0L;

    /**
     * Field freeSpaceOnDisk.
     */
    private long freeSpaceOnDisk = 0L;

    /**
     * Field fileCountInRepository.
     */
    private long fileCountInRepository = 0L;

    /**
     * Field notFoundCacheSize.
     */
    private long notFoundCacheSize = 0L;

    /**
     * Field notFoundCacheHits.
     */
    private long notFoundCacheHits = 0L;

    /**
     * Field notFoundCacheMisses.
     */
    private long notFoundCacheMisses = 0L;

    /**
     * Field localStorageErrorsCount.
     */
    private int localStorageErrorsCount = 0;

    /**
     * Field remoteStorageErrorsCount.
     */
    private int remoteStorageErrorsCount = 0;

    /**
     * Field groups.
     */
    private java.util.List<String> groups;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addGroup.
     * 
     * @param string
     */
    public void addGroup( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "RepositoryMetaResource.addGroups(string) parameter must be instanceof " + String.class.getName() );
        }
        getGroups().add( string );
    } //-- void addGroup( String )

    /**
     * Get the fileCountInRepository field.
     * 
     * @return long
     */
    public long getFileCountInRepository()
    {
        return this.fileCountInRepository;
    } //-- long getFileCountInRepository()

    /**
     * Get the format field.
     * 
     * @return String
     */
    public String getFormat()
    {
        return this.format;
    } //-- String getFormat()

    /**
     * Get the freeSpaceOnDisk field.
     * 
     * @return long
     */
    public long getFreeSpaceOnDisk()
    {
        return this.freeSpaceOnDisk;
    } //-- long getFreeSpaceOnDisk()

    /**
     * Method getGroups.
     * 
     * @return List
     */
    public java.util.List<String> getGroups()
    {
        if ( this.groups == null )
        {
            this.groups = new java.util.ArrayList<String>();
        }

        return this.groups;
    } //-- java.util.List<String> getGroups()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the localStorageErrorsCount field.
     * 
     * @return int
     */
    public int getLocalStorageErrorsCount()
    {
        return this.localStorageErrorsCount;
    } //-- int getLocalStorageErrorsCount()

    /**
     * Get the notFoundCacheHits field.
     * 
     * @return long
     */
    public long getNotFoundCacheHits()
    {
        return this.notFoundCacheHits;
    } //-- long getNotFoundCacheHits()

    /**
     * Get the notFoundCacheMisses field.
     * 
     * @return long
     */
    public long getNotFoundCacheMisses()
    {
        return this.notFoundCacheMisses;
    } //-- long getNotFoundCacheMisses()

    /**
     * Get the notFoundCacheSize field.
     * 
     * @return long
     */
    public long getNotFoundCacheSize()
    {
        return this.notFoundCacheSize;
    } //-- long getNotFoundCacheSize()

    /**
     * Get the remoteStorageErrorsCount field.
     * 
     * @return int
     */
    public int getRemoteStorageErrorsCount()
    {
        return this.remoteStorageErrorsCount;
    } //-- int getRemoteStorageErrorsCount()

    /**
     * Get the repoType field.
     * 
     * @return String
     */
    public String getRepoType()
    {
        return this.repoType;
    } //-- String getRepoType()

    /**
     * Get the sizeOnDisk field.
     * 
     * @return long
     */
    public long getSizeOnDisk()
    {
        return this.sizeOnDisk;
    } //-- long getSizeOnDisk()

    /**
     * Method removeGroup.
     * 
     * @param string
     */
    public void removeGroup( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "RepositoryMetaResource.removeGroups(string) parameter must be instanceof " + String.class.getName() );
        }
        getGroups().remove( string );
    } //-- void removeGroup( String )

    /**
     * Set the fileCountInRepository field.
     * 
     * @param fileCountInRepository
     */
    public void setFileCountInRepository( long fileCountInRepository )
    {
        this.fileCountInRepository = fileCountInRepository;
    } //-- void setFileCountInRepository( long )

    /**
     * Set the format field.
     * 
     * @param format
     */
    public void setFormat( String format )
    {
        this.format = format;
    } //-- void setFormat( String )

    /**
     * Set the freeSpaceOnDisk field.
     * 
     * @param freeSpaceOnDisk
     */
    public void setFreeSpaceOnDisk( long freeSpaceOnDisk )
    {
        this.freeSpaceOnDisk = freeSpaceOnDisk;
    } //-- void setFreeSpaceOnDisk( long )

    /**
     * Set the groups field.
     * 
     * @param groups
     */
    public void setGroups( java.util.List<String> groups )
    {
        this.groups = groups;
    } //-- void setGroups( java.util.List )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the localStorageErrorsCount field.
     * 
     * @param localStorageErrorsCount
     */
    public void setLocalStorageErrorsCount( int localStorageErrorsCount )
    {
        this.localStorageErrorsCount = localStorageErrorsCount;
    } //-- void setLocalStorageErrorsCount( int )

    /**
     * Set the notFoundCacheHits field.
     * 
     * @param notFoundCacheHits
     */
    public void setNotFoundCacheHits( long notFoundCacheHits )
    {
        this.notFoundCacheHits = notFoundCacheHits;
    } //-- void setNotFoundCacheHits( long )

    /**
     * Set the notFoundCacheMisses field.
     * 
     * @param notFoundCacheMisses
     */
    public void setNotFoundCacheMisses( long notFoundCacheMisses )
    {
        this.notFoundCacheMisses = notFoundCacheMisses;
    } //-- void setNotFoundCacheMisses( long )

    /**
     * Set the notFoundCacheSize field.
     * 
     * @param notFoundCacheSize
     */
    public void setNotFoundCacheSize( long notFoundCacheSize )
    {
        this.notFoundCacheSize = notFoundCacheSize;
    } //-- void setNotFoundCacheSize( long )

    /**
     * Set the remoteStorageErrorsCount field.
     * 
     * @param remoteStorageErrorsCount
     */
    public void setRemoteStorageErrorsCount( int remoteStorageErrorsCount )
    {
        this.remoteStorageErrorsCount = remoteStorageErrorsCount;
    } //-- void setRemoteStorageErrorsCount( int )

    /**
     * Set the repoType field.
     * 
     * @param repoType
     */
    public void setRepoType( String repoType )
    {
        this.repoType = repoType;
    } //-- void setRepoType( String )

    /**
     * Set the sizeOnDisk field.
     * 
     * @param sizeOnDisk
     */
    public void setSizeOnDisk( long sizeOnDisk )
    {
        this.sizeOnDisk = sizeOnDisk;
    } //-- void setSizeOnDisk( long )


}
