/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class RepositoryRouteResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class RepositoryRouteResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private RepositoryRouteResource data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the data field.
     * 
     * @return RepositoryRouteResource
     */
    public RepositoryRouteResource getData()
    {
        return this.data;
    } //-- RepositoryRouteResource getData()

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( RepositoryRouteResource data )
    {
        this.data = data;
    } //-- void setData( RepositoryRouteResource )


}
