/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceTypePropertyResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceTypePropertyResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field id.
     */
    private String id;

    /**
     * Field name.
     */
    private String name;

    /**
     * Field type.
     */
    private String type;

    /**
     * Field helpText.
     */
    private String helpText;

    /**
     * Field required.
     */
    private boolean required = false;

    /**
     * Field regexValidation.
     */
    private String regexValidation;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the helpText field.
     * 
     * @return String
     */
    public String getHelpText()
    {
        return this.helpText;
    } //-- String getHelpText()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the name field.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Get the regexValidation field.
     * 
     * @return String
     */
    public String getRegexValidation()
    {
        return this.regexValidation;
    } //-- String getRegexValidation()

    /**
     * Get the type field.
     * 
     * @return String
     */
    public String getType()
    {
        return this.type;
    } //-- String getType()

    /**
     * Get the required field.
     * 
     * @return boolean
     */
    public boolean isRequired()
    {
        return this.required;
    } //-- boolean isRequired()

    /**
     * Set the helpText field.
     * 
     * @param helpText
     */
    public void setHelpText( String helpText )
    {
        this.helpText = helpText;
    } //-- void setHelpText( String )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the name field.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set the regexValidation field.
     * 
     * @param regexValidation
     */
    public void setRegexValidation( String regexValidation )
    {
        this.regexValidation = regexValidation;
    } //-- void setRegexValidation( String )

    /**
     * Set the required field.
     * 
     * @param required
     */
    public void setRequired( boolean required )
    {
        this.required = required;
    } //-- void setRequired( boolean )

    /**
     * Set the type field.
     * 
     * @param type
     */
    public void setType( String type )
    {
        this.type = type;
    } //-- void setType( String )


}
