/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceOnceResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceOnceResource
    extends ScheduledServiceBaseResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field startDate.
     */
    private String startDate;

    /**
     * Field startTime.
     */
    private String startTime;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the startDate field.
     * 
     * @return String
     */
    public String getStartDate()
    {
        return this.startDate;
    } //-- String getStartDate()

    /**
     * Get the startTime field.
     * 
     * @return String
     */
    public String getStartTime()
    {
        return this.startTime;
    } //-- String getStartTime()

    /**
     * Set the startDate field.
     * 
     * @param startDate
     */
    public void setStartDate( String startDate )
    {
        this.startDate = startDate;
    } //-- void setStartDate( String )

    /**
     * Set the startTime field.
     * 
     * @param startTime
     */
    public void setStartTime( String startTime )
    {
        this.startTime = startTime;
    } //-- void setStartTime( String )


}
