/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceAdvancedResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceAdvancedResource
    extends ScheduledServiceBaseResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field cronCommand.
     */
    private String cronCommand;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the cronCommand field.
     * 
     * @return String
     */
    public String getCronCommand()
    {
        return this.cronCommand;
    } //-- String getCronCommand()

    /**
     * Set the cronCommand field.
     * 
     * @param cronCommand
     */
    public void setCronCommand( String cronCommand )
    {
        this.cronCommand = cronCommand;
    } //-- void setCronCommand( String )


}
