/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceTypeResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceTypeResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field id.
     */
    private String id;

    /**
     * Field name.
     */
    private String name;

    /**
     * Field properties.
     */
    private java.util.List<ScheduledServiceTypePropertyResource> properties;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addProperty.
     * 
     * @param scheduledServiceTypePropertyResource
     */
    public void addProperty( ScheduledServiceTypePropertyResource scheduledServiceTypePropertyResource )
    {
        if ( !(scheduledServiceTypePropertyResource instanceof ScheduledServiceTypePropertyResource) )
        {
            throw new ClassCastException( "ScheduledServiceTypeResource.addProperties(scheduledServiceTypePropertyResource) parameter must be instanceof " + ScheduledServiceTypePropertyResource.class.getName() );
        }
        getProperties().add( scheduledServiceTypePropertyResource );
    } //-- void addProperty( ScheduledServiceTypePropertyResource )

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the name field.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Method getProperties.
     * 
     * @return List
     */
    public java.util.List<ScheduledServiceTypePropertyResource> getProperties()
    {
        if ( this.properties == null )
        {
            this.properties = new java.util.ArrayList<ScheduledServiceTypePropertyResource>();
        }

        return this.properties;
    } //-- java.util.List<ScheduledServiceTypePropertyResource> getProperties()

    /**
     * Method removeProperty.
     * 
     * @param scheduledServiceTypePropertyResource
     */
    public void removeProperty( ScheduledServiceTypePropertyResource scheduledServiceTypePropertyResource )
    {
        if ( !(scheduledServiceTypePropertyResource instanceof ScheduledServiceTypePropertyResource) )
        {
            throw new ClassCastException( "ScheduledServiceTypeResource.removeProperties(scheduledServiceTypePropertyResource) parameter must be instanceof " + ScheduledServiceTypePropertyResource.class.getName() );
        }
        getProperties().remove( scheduledServiceTypePropertyResource );
    } //-- void removeProperty( ScheduledServiceTypePropertyResource )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the name field.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set the properties field.
     * 
     * @param properties
     */
    public void setProperties( java.util.List<ScheduledServiceTypePropertyResource> properties )
    {
        this.properties = properties;
    } //-- void setProperties( java.util.List )


}
