/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceResourceStatus.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceResourceStatus
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field resource.
     */
    private ScheduledServiceBaseResource resource;

    /**
     * Field resourceURI.
     */
    private String resourceURI;

    /**
     * Field status.
     */
    private String status;

    /**
     * Field nextRunTime.
     */
    private String nextRunTime;

    /**
     * Field lastRunTime.
     */
    private String lastRunTime;

    /**
     * Field lastRunResult.
     */
    private String lastRunResult;

    /**
     * Field created.
     */
    private String created;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the created field.
     * 
     * @return String
     */
    public String getCreated()
    {
        return this.created;
    } //-- String getCreated()

    /**
     * Get the lastRunResult field.
     * 
     * @return String
     */
    public String getLastRunResult()
    {
        return this.lastRunResult;
    } //-- String getLastRunResult()

    /**
     * Get the lastRunTime field.
     * 
     * @return String
     */
    public String getLastRunTime()
    {
        return this.lastRunTime;
    } //-- String getLastRunTime()

    /**
     * Get the nextRunTime field.
     * 
     * @return String
     */
    public String getNextRunTime()
    {
        return this.nextRunTime;
    } //-- String getNextRunTime()

    /**
     * Get the resource field.
     * 
     * @return ScheduledServiceBaseResource
     */
    public ScheduledServiceBaseResource getResource()
    {
        return this.resource;
    } //-- ScheduledServiceBaseResource getResource()

    /**
     * Get the resourceURI field.
     * 
     * @return String
     */
    public String getResourceURI()
    {
        return this.resourceURI;
    } //-- String getResourceURI()

    /**
     * Get the status field.
     * 
     * @return String
     */
    public String getStatus()
    {
        return this.status;
    } //-- String getStatus()

    /**
     * Set the created field.
     * 
     * @param created
     */
    public void setCreated( String created )
    {
        this.created = created;
    } //-- void setCreated( String )

    /**
     * Set the lastRunResult field.
     * 
     * @param lastRunResult
     */
    public void setLastRunResult( String lastRunResult )
    {
        this.lastRunResult = lastRunResult;
    } //-- void setLastRunResult( String )

    /**
     * Set the lastRunTime field.
     * 
     * @param lastRunTime
     */
    public void setLastRunTime( String lastRunTime )
    {
        this.lastRunTime = lastRunTime;
    } //-- void setLastRunTime( String )

    /**
     * Set the nextRunTime field.
     * 
     * @param nextRunTime
     */
    public void setNextRunTime( String nextRunTime )
    {
        this.nextRunTime = nextRunTime;
    } //-- void setNextRunTime( String )

    /**
     * Set the resource field.
     * 
     * @param resource
     */
    public void setResource( ScheduledServiceBaseResource resource )
    {
        this.resource = resource;
    } //-- void setResource( ScheduledServiceBaseResource )

    /**
     * Set the resourceURI field.
     * 
     * @param resourceURI
     */
    public void setResourceURI( String resourceURI )
    {
        this.resourceURI = resourceURI;
    } //-- void setResourceURI( String )

    /**
     * Set the status field.
     * 
     * @param status
     */
    public void setStatus( String status )
    {
        this.status = status;
    } //-- void setStatus( String )


}
