/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceBaseResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceBaseResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field id.
     */
    private String id;

    /**
     * Field name.
     */
    private String name;

    /**
     * Field enabled.
     */
    private boolean enabled = false;

    /**
     * Field typeId.
     */
    private String typeId;

    /**
     * Field alertEmail.
     */
    private String alertEmail;

    /**
     * Field schedule.
     */
    private String schedule;

    /**
     * Field properties.
     */
    private java.util.List<ScheduledServicePropertyResource> properties;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addProperty.
     * 
     * @param scheduledServicePropertyResource
     */
    public void addProperty( ScheduledServicePropertyResource scheduledServicePropertyResource )
    {
        if ( !(scheduledServicePropertyResource instanceof ScheduledServicePropertyResource) )
        {
            throw new ClassCastException( "ScheduledServiceBaseResource.addProperties(scheduledServicePropertyResource) parameter must be instanceof " + ScheduledServicePropertyResource.class.getName() );
        }
        getProperties().add( scheduledServicePropertyResource );
    } //-- void addProperty( ScheduledServicePropertyResource )

    /**
     * Get the alertEmail field.
     * 
     * @return String
     */
    public String getAlertEmail()
    {
        return this.alertEmail;
    } //-- String getAlertEmail()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the name field.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Method getProperties.
     * 
     * @return List
     */
    public java.util.List<ScheduledServicePropertyResource> getProperties()
    {
        if ( this.properties == null )
        {
            this.properties = new java.util.ArrayList<ScheduledServicePropertyResource>();
        }

        return this.properties;
    } //-- java.util.List<ScheduledServicePropertyResource> getProperties()

    /**
     * Get the schedule field.
     * 
     * @return String
     */
    public String getSchedule()
    {
        return this.schedule;
    } //-- String getSchedule()

    /**
     * Get the typeId field.
     * 
     * @return String
     */
    public String getTypeId()
    {
        return this.typeId;
    } //-- String getTypeId()

    /**
     * Get the enabled field.
     * 
     * @return boolean
     */
    public boolean isEnabled()
    {
        return this.enabled;
    } //-- boolean isEnabled()

    /**
     * Method removeProperty.
     * 
     * @param scheduledServicePropertyResource
     */
    public void removeProperty( ScheduledServicePropertyResource scheduledServicePropertyResource )
    {
        if ( !(scheduledServicePropertyResource instanceof ScheduledServicePropertyResource) )
        {
            throw new ClassCastException( "ScheduledServiceBaseResource.removeProperties(scheduledServicePropertyResource) parameter must be instanceof " + ScheduledServicePropertyResource.class.getName() );
        }
        getProperties().remove( scheduledServicePropertyResource );
    } //-- void removeProperty( ScheduledServicePropertyResource )

    /**
     * Set the alertEmail field.
     * 
     * @param alertEmail
     */
    public void setAlertEmail( String alertEmail )
    {
        this.alertEmail = alertEmail;
    } //-- void setAlertEmail( String )

    /**
     * Set the enabled field.
     * 
     * @param enabled
     */
    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    } //-- void setEnabled( boolean )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the name field.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set the properties field.
     * 
     * @param properties
     */
    public void setProperties( java.util.List<ScheduledServicePropertyResource> properties )
    {
        this.properties = properties;
    } //-- void setProperties( java.util.List )

    /**
     * Set the schedule field.
     * 
     * @param schedule
     */
    public void setSchedule( String schedule )
    {
        this.schedule = schedule;
    } //-- void setSchedule( String )

    /**
     * Set the typeId field.
     * 
     * @param typeId
     */
    public void setTypeId( String typeId )
    {
        this.typeId = typeId;
    } //-- void setTypeId( String )


}
