/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceListResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceListResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field resourceURI.
     */
    private String resourceURI;

    /**
     * Field id.
     */
    private String id;

    /**
     * Field enabled.
     */
    private boolean enabled = false;

    /**
     * Field name.
     */
    private String name;

    /**
     * Field typeId.
     */
    private String typeId;

    /**
     * Field typeName.
     */
    private String typeName;

    /**
     * Field status.
     */
    private String status;

    /**
     * Field schedule.
     */
    private String schedule;

    /**
     * Field nextRunTime.
     */
    private String nextRunTime;

    /**
     * Field lastRunTime.
     */
    private String lastRunTime;

    /**
     * Field lastRunResult.
     */
    private String lastRunResult;

    /**
     * Field created.
     */
    private String created;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the created field.
     * 
     * @return String
     */
    public String getCreated()
    {
        return this.created;
    } //-- String getCreated()

    /**
     * Get the id field.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get the lastRunResult field.
     * 
     * @return String
     */
    public String getLastRunResult()
    {
        return this.lastRunResult;
    } //-- String getLastRunResult()

    /**
     * Get the lastRunTime field.
     * 
     * @return String
     */
    public String getLastRunTime()
    {
        return this.lastRunTime;
    } //-- String getLastRunTime()

    /**
     * Get the name field.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Get the nextRunTime field.
     * 
     * @return String
     */
    public String getNextRunTime()
    {
        return this.nextRunTime;
    } //-- String getNextRunTime()

    /**
     * Get the resourceURI field.
     * 
     * @return String
     */
    public String getResourceURI()
    {
        return this.resourceURI;
    } //-- String getResourceURI()

    /**
     * Get the schedule field.
     * 
     * @return String
     */
    public String getSchedule()
    {
        return this.schedule;
    } //-- String getSchedule()

    /**
     * Get the status field.
     * 
     * @return String
     */
    public String getStatus()
    {
        return this.status;
    } //-- String getStatus()

    /**
     * Get the typeId field.
     * 
     * @return String
     */
    public String getTypeId()
    {
        return this.typeId;
    } //-- String getTypeId()

    /**
     * Get the typeName field.
     * 
     * @return String
     */
    public String getTypeName()
    {
        return this.typeName;
    } //-- String getTypeName()

    /**
     * Get the enabled field.
     * 
     * @return boolean
     */
    public boolean isEnabled()
    {
        return this.enabled;
    } //-- boolean isEnabled()

    /**
     * Set the created field.
     * 
     * @param created
     */
    public void setCreated( String created )
    {
        this.created = created;
    } //-- void setCreated( String )

    /**
     * Set the enabled field.
     * 
     * @param enabled
     */
    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    } //-- void setEnabled( boolean )

    /**
     * Set the id field.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set the lastRunResult field.
     * 
     * @param lastRunResult
     */
    public void setLastRunResult( String lastRunResult )
    {
        this.lastRunResult = lastRunResult;
    } //-- void setLastRunResult( String )

    /**
     * Set the lastRunTime field.
     * 
     * @param lastRunTime
     */
    public void setLastRunTime( String lastRunTime )
    {
        this.lastRunTime = lastRunTime;
    } //-- void setLastRunTime( String )

    /**
     * Set the name field.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set the nextRunTime field.
     * 
     * @param nextRunTime
     */
    public void setNextRunTime( String nextRunTime )
    {
        this.nextRunTime = nextRunTime;
    } //-- void setNextRunTime( String )

    /**
     * Set the resourceURI field.
     * 
     * @param resourceURI
     */
    public void setResourceURI( String resourceURI )
    {
        this.resourceURI = resourceURI;
    } //-- void setResourceURI( String )

    /**
     * Set the schedule field.
     * 
     * @param schedule
     */
    public void setSchedule( String schedule )
    {
        this.schedule = schedule;
    } //-- void setSchedule( String )

    /**
     * Set the status field.
     * 
     * @param status
     */
    public void setStatus( String status )
    {
        this.status = status;
    } //-- void setStatus( String )

    /**
     * Set the typeId field.
     * 
     * @param typeId
     */
    public void setTypeId( String typeId )
    {
        this.typeId = typeId;
    } //-- void setTypeId( String )

    /**
     * Set the typeName field.
     * 
     * @param typeName
     */
    public void setTypeName( String typeName )
    {
        this.typeName = typeName;
    } //-- void setTypeName( String )


}
