/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceWeeklyResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceWeeklyResource
    extends ScheduledServiceDailyResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field recurringDay.
     */
    private java.util.List<String> recurringDay;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addRecurringDay.
     * 
     * @param string
     */
    public void addRecurringDay( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "ScheduledServiceWeeklyResource.addRecurringDay(string) parameter must be instanceof " + String.class.getName() );
        }
        getRecurringDay().add( string );
    } //-- void addRecurringDay( String )

    /**
     * Method getRecurringDay.
     * 
     * @return List
     */
    public java.util.List<String> getRecurringDay()
    {
        if ( this.recurringDay == null )
        {
            this.recurringDay = new java.util.ArrayList<String>();
        }

        return this.recurringDay;
    } //-- java.util.List<String> getRecurringDay()

    /**
     * Method removeRecurringDay.
     * 
     * @param string
     */
    public void removeRecurringDay( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "ScheduledServiceWeeklyResource.removeRecurringDay(string) parameter must be instanceof " + String.class.getName() );
        }
        getRecurringDay().remove( string );
    } //-- void removeRecurringDay( String )

    /**
     * Set the recurringDay field.
     * 
     * @param recurringDay
     */
    public void setRecurringDay( java.util.List<String> recurringDay )
    {
        this.recurringDay = recurringDay;
    } //-- void setRecurringDay( java.util.List )


}
