/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceTypeResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceTypeResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<ScheduledServiceTypeResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param scheduledServiceTypeResource
     */
    public void addData( ScheduledServiceTypeResource scheduledServiceTypeResource )
    {
        if ( !(scheduledServiceTypeResource instanceof ScheduledServiceTypeResource) )
        {
            throw new ClassCastException( "ScheduledServiceTypeResourceResponse.addData(scheduledServiceTypeResource) parameter must be instanceof " + ScheduledServiceTypeResource.class.getName() );
        }
        getData().add( scheduledServiceTypeResource );
    } //-- void addData( ScheduledServiceTypeResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<ScheduledServiceTypeResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<ScheduledServiceTypeResource>();
        }

        return this.data;
    } //-- java.util.List<ScheduledServiceTypeResource> getData()

    /**
     * Method removeData.
     * 
     * @param scheduledServiceTypeResource
     */
    public void removeData( ScheduledServiceTypeResource scheduledServiceTypeResource )
    {
        if ( !(scheduledServiceTypeResource instanceof ScheduledServiceTypeResource) )
        {
            throw new ClassCastException( "ScheduledServiceTypeResourceResponse.removeData(scheduledServiceTypeResource) parameter must be instanceof " + ScheduledServiceTypeResource.class.getName() );
        }
        getData().remove( scheduledServiceTypeResource );
    } //-- void removeData( ScheduledServiceTypeResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<ScheduledServiceTypeResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
