/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceDailyResource.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceDailyResource
    extends ScheduledServiceBaseResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field startDate.
     */
    private String startDate;

    /**
     * Field recurringTime.
     */
    private String recurringTime;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the recurringTime field.
     * 
     * @return String
     */
    public String getRecurringTime()
    {
        return this.recurringTime;
    } //-- String getRecurringTime()

    /**
     * Get the startDate field.
     * 
     * @return String
     */
    public String getStartDate()
    {
        return this.startDate;
    } //-- String getStartDate()

    /**
     * Set the recurringTime field.
     * 
     * @param recurringTime
     */
    public void setRecurringTime( String recurringTime )
    {
        this.recurringTime = recurringTime;
    } //-- void setRecurringTime( String )

    /**
     * Set the startDate field.
     * 
     * @param startDate
     */
    public void setStartDate( String startDate )
    {
        this.startDate = startDate;
    } //-- void setStartDate( String )


}
