/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class ScheduledServiceListResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
public class ScheduledServiceListResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private java.util.List<ScheduledServiceListResource> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param scheduledServiceListResource
     */
    public void addData( ScheduledServiceListResource scheduledServiceListResource )
    {
        if ( !(scheduledServiceListResource instanceof ScheduledServiceListResource) )
        {
            throw new ClassCastException( "ScheduledServiceListResourceResponse.addData(scheduledServiceListResource) parameter must be instanceof " + ScheduledServiceListResource.class.getName() );
        }
        getData().add( scheduledServiceListResource );
    } //-- void addData( ScheduledServiceListResource )

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<ScheduledServiceListResource> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<ScheduledServiceListResource>();
        }

        return this.data;
    } //-- java.util.List<ScheduledServiceListResource> getData()

    /**
     * Method removeData.
     * 
     * @param scheduledServiceListResource
     */
    public void removeData( ScheduledServiceListResource scheduledServiceListResource )
    {
        if ( !(scheduledServiceListResource instanceof ScheduledServiceListResource) )
        {
            throw new ClassCastException( "ScheduledServiceListResourceResponse.removeData(scheduledServiceListResource) parameter must be instanceof " + ScheduledServiceListResource.class.getName() );
        }
        getData().remove( scheduledServiceListResource );
    } //-- void removeData( ScheduledServiceListResource )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<ScheduledServiceListResource> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )


}
