/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class SearchResponse.
 * 
 * @version $Revision$ $Date$
 */
public class SearchResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field totalCount.
     */
    private int totalCount = 0;

    /**
     * Field from.
     */
    private int from = 0;

    /**
     * Field count.
     */
    private int count = 0;

    /**
     * Field tooManyResults.
     */
    private boolean tooManyResults = false;

    /**
     * Field data.
     */
    private java.util.List<NexusArtifact> data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addData.
     * 
     * @param nexusArtifact
     */
    public void addData( NexusArtifact nexusArtifact )
    {
        if ( !(nexusArtifact instanceof NexusArtifact) )
        {
            throw new ClassCastException( "SearchResponse.addData(nexusArtifact) parameter must be instanceof " + NexusArtifact.class.getName() );
        }
        getData().add( nexusArtifact );
    } //-- void addData( NexusArtifact )

    /**
     * Get the count field.
     * 
     * @return int
     */
    public int getCount()
    {
        return this.count;
    } //-- int getCount()

    /**
     * Method getData.
     * 
     * @return List
     */
    public java.util.List<NexusArtifact> getData()
    {
        if ( this.data == null )
        {
            this.data = new java.util.ArrayList<NexusArtifact>();
        }

        return this.data;
    } //-- java.util.List<NexusArtifact> getData()

    /**
     * Get the from field.
     * 
     * @return int
     */
    public int getFrom()
    {
        return this.from;
    } //-- int getFrom()

    /**
     * Get the totalCount field.
     * 
     * @return int
     */
    public int getTotalCount()
    {
        return this.totalCount;
    } //-- int getTotalCount()

    /**
     * Get the tooManyResults field.
     * 
     * @return boolean
     */
    public boolean isTooManyResults()
    {
        return this.tooManyResults;
    } //-- boolean isTooManyResults()

    /**
     * Method removeData.
     * 
     * @param nexusArtifact
     */
    public void removeData( NexusArtifact nexusArtifact )
    {
        if ( !(nexusArtifact instanceof NexusArtifact) )
        {
            throw new ClassCastException( "SearchResponse.removeData(nexusArtifact) parameter must be instanceof " + NexusArtifact.class.getName() );
        }
        getData().remove( nexusArtifact );
    } //-- void removeData( NexusArtifact )

    /**
     * Set the count field.
     * 
     * @param count
     */
    public void setCount( int count )
    {
        this.count = count;
    } //-- void setCount( int )

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( java.util.List<NexusArtifact> data )
    {
        this.data = data;
    } //-- void setData( java.util.List )

    /**
     * Set the from field.
     * 
     * @param from
     */
    public void setFrom( int from )
    {
        this.from = from;
    } //-- void setFrom( int )

    /**
     * Set the tooManyResults field.
     * 
     * @param tooManyResults
     */
    public void setTooManyResults( boolean tooManyResults )
    {
        this.tooManyResults = tooManyResults;
    } //-- void setTooManyResults( boolean )

    /**
     * Set the totalCount field.
     * 
     * @param totalCount
     */
    public void setTotalCount( int totalCount )
    {
        this.totalCount = totalCount;
    } //-- void setTotalCount( int )


}
