/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Class StatusResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
@XmlRootElement(name="repository-status")
public class StatusResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field data.
     */
    private StatusResource data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the data field.
     * 
     * @return StatusResource
     */
    public StatusResource getData()
    {
        return this.data;
    } //-- StatusResource getData()

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( StatusResource data )
    {
        this.data = data;
    } //-- void setData( StatusResource )


}
