/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class StatusResource.
 * 
 * @version $Revision$ $Date$
 */
public class StatusResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field appName.
     */
    private String appName;

    /**
     * Field formattedAppName.
     */
    private String formattedAppName;

    /**
     * Field version.
     */
    private String version;

    /**
     * Field apiVersion.
     */
    private String apiVersion;

    /**
     * Field editionLong.
     */
    private String editionLong;

    /**
     * Field editionShort.
     */
    private String editionShort;

    /**
     * Field state.
     */
    private String state;

    /**
     * Field operationMode.
     */
    private String operationMode;

    /**
     * Field initializedAt.
     */
    private java.util.Date initializedAt;

    /**
     * Field startedAt.
     */
    private java.util.Date startedAt;

    /**
     * Field lastConfigChange.
     */
    private java.util.Date lastConfigChange;

    /**
     * Field firstStart.
     */
    private boolean firstStart = false;

    /**
     * Field instanceUpgraded.
     */
    private boolean instanceUpgraded = false;

    /**
     * Field configurationUpgraded.
     */
    private boolean configurationUpgraded = false;

    /**
     * Field configurationValidationResponse.
     */
    private StatusConfigurationValidationResponse configurationValidationResponse;

    /**
     * Field errorCause.
     */
    private String errorCause;

    /**
     * Field clientPermissions.
     */
    private NexusAuthenticationClientPermissions clientPermissions;

    /**
     * Field baseUrl.
     */
    private String baseUrl;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the apiVersion field.
     * 
     * @return String
     */
    public String getApiVersion()
    {
        return this.apiVersion;
    } //-- String getApiVersion()

    /**
     * Get the appName field.
     * 
     * @return String
     */
    public String getAppName()
    {
        return this.appName;
    } //-- String getAppName()

    /**
     * Get the baseUrl field.
     * 
     * @return String
     */
    public String getBaseUrl()
    {
        return this.baseUrl;
    } //-- String getBaseUrl()

    /**
     * Get the clientPermissions field.
     * 
     * @return NexusAuthenticationClientPermissions
     */
    public NexusAuthenticationClientPermissions getClientPermissions()
    {
        return this.clientPermissions;
    } //-- NexusAuthenticationClientPermissions getClientPermissions()

    /**
     * Get the configurationValidationResponse field.
     * 
     * @return StatusConfigurationValidationResponse
     */
    public StatusConfigurationValidationResponse getConfigurationValidationResponse()
    {
        return this.configurationValidationResponse;
    } //-- StatusConfigurationValidationResponse getConfigurationValidationResponse()

    /**
     * Get the editionLong field.
     * 
     * @return String
     */
    public String getEditionLong()
    {
        return this.editionLong;
    } //-- String getEditionLong()

    /**
     * Get the editionShort field.
     * 
     * @return String
     */
    public String getEditionShort()
    {
        return this.editionShort;
    } //-- String getEditionShort()

    /**
     * Get the errorCause field.
     * 
     * @return String
     */
    public String getErrorCause()
    {
        return this.errorCause;
    } //-- String getErrorCause()

    /**
     * Get the formattedAppName field.
     * 
     * @return String
     */
    public String getFormattedAppName()
    {
        return this.formattedAppName;
    } //-- String getFormattedAppName()

    /**
     * Get the initializedAt field.
     * 
     * @return Date
     */
    public java.util.Date getInitializedAt()
    {
        return this.initializedAt;
    } //-- java.util.Date getInitializedAt()

    /**
     * Get the lastConfigChange field.
     * 
     * @return Date
     */
    public java.util.Date getLastConfigChange()
    {
        return this.lastConfigChange;
    } //-- java.util.Date getLastConfigChange()

    /**
     * Get the operationMode field.
     * 
     * @return String
     */
    public String getOperationMode()
    {
        return this.operationMode;
    } //-- String getOperationMode()

    /**
     * Get the startedAt field.
     * 
     * @return Date
     */
    public java.util.Date getStartedAt()
    {
        return this.startedAt;
    } //-- java.util.Date getStartedAt()

    /**
     * Get the state field.
     * 
     * @return String
     */
    public String getState()
    {
        return this.state;
    } //-- String getState()

    /**
     * Get the version field.
     * 
     * @return String
     */
    public String getVersion()
    {
        return this.version;
    } //-- String getVersion()

    /**
     * Get the configurationUpgraded field.
     * 
     * @return boolean
     */
    public boolean isConfigurationUpgraded()
    {
        return this.configurationUpgraded;
    } //-- boolean isConfigurationUpgraded()

    /**
     * Get the firstStart field.
     * 
     * @return boolean
     */
    public boolean isFirstStart()
    {
        return this.firstStart;
    } //-- boolean isFirstStart()

    /**
     * Get the instanceUpgraded field.
     * 
     * @return boolean
     */
    public boolean isInstanceUpgraded()
    {
        return this.instanceUpgraded;
    } //-- boolean isInstanceUpgraded()

    /**
     * Set the apiVersion field.
     * 
     * @param apiVersion
     */
    public void setApiVersion( String apiVersion )
    {
        this.apiVersion = apiVersion;
    } //-- void setApiVersion( String )

    /**
     * Set the appName field.
     * 
     * @param appName
     */
    public void setAppName( String appName )
    {
        this.appName = appName;
    } //-- void setAppName( String )

    /**
     * Set the baseUrl field.
     * 
     * @param baseUrl
     */
    public void setBaseUrl( String baseUrl )
    {
        this.baseUrl = baseUrl;
    } //-- void setBaseUrl( String )

    /**
     * Set the clientPermissions field.
     * 
     * @param clientPermissions
     */
    public void setClientPermissions( NexusAuthenticationClientPermissions clientPermissions )
    {
        this.clientPermissions = clientPermissions;
    } //-- void setClientPermissions( NexusAuthenticationClientPermissions )

    /**
     * Set the configurationUpgraded field.
     * 
     * @param configurationUpgraded
     */
    public void setConfigurationUpgraded( boolean configurationUpgraded )
    {
        this.configurationUpgraded = configurationUpgraded;
    } //-- void setConfigurationUpgraded( boolean )

    /**
     * Set the configurationValidationResponse field.
     * 
     * @param configurationValidationResponse
     */
    public void setConfigurationValidationResponse( StatusConfigurationValidationResponse configurationValidationResponse )
    {
        this.configurationValidationResponse = configurationValidationResponse;
    } //-- void setConfigurationValidationResponse( StatusConfigurationValidationResponse )

    /**
     * Set the editionLong field.
     * 
     * @param editionLong
     */
    public void setEditionLong( String editionLong )
    {
        this.editionLong = editionLong;
    } //-- void setEditionLong( String )

    /**
     * Set the editionShort field.
     * 
     * @param editionShort
     */
    public void setEditionShort( String editionShort )
    {
        this.editionShort = editionShort;
    } //-- void setEditionShort( String )

    /**
     * Set the errorCause field.
     * 
     * @param errorCause
     */
    public void setErrorCause( String errorCause )
    {
        this.errorCause = errorCause;
    } //-- void setErrorCause( String )

    /**
     * Set the firstStart field.
     * 
     * @param firstStart
     */
    public void setFirstStart( boolean firstStart )
    {
        this.firstStart = firstStart;
    } //-- void setFirstStart( boolean )

    /**
     * Set the formattedAppName field.
     * 
     * @param formattedAppName
     */
    public void setFormattedAppName( String formattedAppName )
    {
        this.formattedAppName = formattedAppName;
    } //-- void setFormattedAppName( String )

    /**
     * Set the initializedAt field.
     * 
     * @param initializedAt
     */
    public void setInitializedAt( java.util.Date initializedAt )
    {
        this.initializedAt = initializedAt;
    } //-- void setInitializedAt( java.util.Date )

    /**
     * Set the instanceUpgraded field.
     * 
     * @param instanceUpgraded
     */
    public void setInstanceUpgraded( boolean instanceUpgraded )
    {
        this.instanceUpgraded = instanceUpgraded;
    } //-- void setInstanceUpgraded( boolean )

    /**
     * Set the lastConfigChange field.
     * 
     * @param lastConfigChange
     */
    public void setLastConfigChange( java.util.Date lastConfigChange )
    {
        this.lastConfigChange = lastConfigChange;
    } //-- void setLastConfigChange( java.util.Date )

    /**
     * Set the operationMode field.
     * 
     * @param operationMode
     */
    public void setOperationMode( String operationMode )
    {
        this.operationMode = operationMode;
    } //-- void setOperationMode( String )

    /**
     * Set the startedAt field.
     * 
     * @param startedAt
     */
    public void setStartedAt( java.util.Date startedAt )
    {
        this.startedAt = startedAt;
    } //-- void setStartedAt( java.util.Date )

    /**
     * Set the state field.
     * 
     * @param state
     */
    public void setState( String state )
    {
        this.state = state;
    } //-- void setState( String )

    /**
     * Set the version field.
     * 
     * @param version
     */
    public void setVersion( String version )
    {
        this.version = version;
    } //-- void setVersion( String )


}
