/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class StatusConfigurationValidationResponse.
 * 
 * @version $Revision$ $Date$
 */
public class StatusConfigurationValidationResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field valid.
     */
    private boolean valid = false;

    /**
     * Field modified.
     */
    private boolean modified = false;

    /**
     * Field validationErrors.
     */
    private java.util.List<String> validationErrors;

    /**
     * Field validationWarnings.
     */
    private java.util.List<String> validationWarnings;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addValidationError.
     * 
     * @param string
     */
    public void addValidationError( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "StatusConfigurationValidationResponse.addValidationErrors(string) parameter must be instanceof " + String.class.getName() );
        }
        getValidationErrors().add( string );
    } //-- void addValidationError( String )

    /**
     * Method addValidationWarning.
     * 
     * @param string
     */
    public void addValidationWarning( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "StatusConfigurationValidationResponse.addValidationWarnings(string) parameter must be instanceof " + String.class.getName() );
        }
        getValidationWarnings().add( string );
    } //-- void addValidationWarning( String )

    /**
     * Method getValidationErrors.
     * 
     * @return List
     */
    public java.util.List<String> getValidationErrors()
    {
        if ( this.validationErrors == null )
        {
            this.validationErrors = new java.util.ArrayList<String>();
        }

        return this.validationErrors;
    } //-- java.util.List<String> getValidationErrors()

    /**
     * Method getValidationWarnings.
     * 
     * @return List
     */
    public java.util.List<String> getValidationWarnings()
    {
        if ( this.validationWarnings == null )
        {
            this.validationWarnings = new java.util.ArrayList<String>();
        }

        return this.validationWarnings;
    } //-- java.util.List<String> getValidationWarnings()

    /**
     * Get the modified field.
     * 
     * @return boolean
     */
    public boolean isModified()
    {
        return this.modified;
    } //-- boolean isModified()

    /**
     * Get the valid field.
     * 
     * @return boolean
     */
    public boolean isValid()
    {
        return this.valid;
    } //-- boolean isValid()

    /**
     * Method removeValidationError.
     * 
     * @param string
     */
    public void removeValidationError( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "StatusConfigurationValidationResponse.removeValidationErrors(string) parameter must be instanceof " + String.class.getName() );
        }
        getValidationErrors().remove( string );
    } //-- void removeValidationError( String )

    /**
     * Method removeValidationWarning.
     * 
     * @param string
     */
    public void removeValidationWarning( String string )
    {
        if ( !(string instanceof String) )
        {
            throw new ClassCastException( "StatusConfigurationValidationResponse.removeValidationWarnings(string) parameter must be instanceof " + String.class.getName() );
        }
        getValidationWarnings().remove( string );
    } //-- void removeValidationWarning( String )

    /**
     * Set the modified field.
     * 
     * @param modified
     */
    public void setModified( boolean modified )
    {
        this.modified = modified;
    } //-- void setModified( boolean )

    /**
     * Set the valid field.
     * 
     * @param valid
     */
    public void setValid( boolean valid )
    {
        this.valid = valid;
    } //-- void setValid( boolean )

    /**
     * Set the validationErrors field.
     * 
     * @param validationErrors
     */
    public void setValidationErrors( java.util.List<String> validationErrors )
    {
        this.validationErrors = validationErrors;
    } //-- void setValidationErrors( java.util.List )

    /**
     * Set the validationWarnings field.
     * 
     * @param validationWarnings
     */
    public void setValidationWarnings( java.util.List<String> validationWarnings )
    {
        this.validationWarnings = validationWarnings;
    } //-- void setValidationWarnings( java.util.List )


}
