/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Class WastebasketResourceResponse.
 * 
 * @version $Revision$ $Date$
 */
@XmlRootElement( name = "wastebasket" )
public class WastebasketResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

    // --------------------------/
    // - Class/Member Variables -/
    // --------------------------/

    /**
     * Field data.
     */
    private WastebasketResource data;

    // -----------/
    // - Methods -/
    // -----------/

    /**
     * Get the data field.
     * 
     * @return WastebasketResource
     */
    public WastebasketResource getData()
    {
        return this.data;
    } // -- WastebasketResource getData()

    /**
     * Set the data field.
     * 
     * @param data
     */
    public void setData( WastebasketResource data )
    {
        this.data = data;
    } // -- void setData( WastebasketResource )

}
