/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2010-01-11 12:09:20,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.rest.model;

/**
 * Class WastebasketResource.
 * 
 * @version $Revision$ $Date$
 */
public class WastebasketResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field size.
     */
    private long size = 0L;

    /**
     * Field itemCount.
     */
    private long itemCount = 0L;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the itemCount field.
     * 
     * @return long
     */
    public long getItemCount()
    {
        return this.itemCount;
    } //-- long getItemCount()

    /**
     * Get the size field.
     * 
     * @return long
     */
    public long getSize()
    {
        return this.size;
    } //-- long getSize()

    /**
     * Set the itemCount field.
     * 
     * @param itemCount
     */
    public void setItemCount( long itemCount )
    {
        this.itemCount = itemCount;
    } //-- void setItemCount( long )

    /**
     * Set the size field.
     * 
     * @param size
     */
    public void setSize( long size )
    {
        this.size = size;
    } //-- void setSize( long )


}
